using System.Numerics;
using System.Threading.Tasks;
using Content.Client.Message;
using Content.Client.Viewport;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using SixLabors.ImageSharp.PixelFormats;

namespace Content.Goobstation.Client.Photo.Ui;

[GenerateTypedNameReferences]
public sealed partial class PhotoWindow : BaseWindow
{
    public Action? ScreenshotTaken;
    public Action<string>? LabelChanged;

    public PhotoWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        CloseButton.OnPressed += args => Close();
        LabelEdit.OnTextEntered += args => LabelChanged?.Invoke(args.Text);
    }

    public void SetLabel(string label)
    {
        LabelEdit.Visible = false;

        if (label != "")
        {
            Label.Visible = true;
            Label.Text = label;
        }
        else
            Label.Visible = false;
    }

    public void ToggleLabelling()
    {
        LabelEdit.Text = Label.Text ?? "";

        Label.Visible = false;
        LabelEdit.Visible = true;
    }

    public async void Populate(MapId map, Vector2 offset)
    {
        FixedEye eye = new()
        {
            Position = new MapCoordinates(offset, map),
            DrawFov = true,
            DrawLight = true,
            Zoom = new(0.3f)
        };

        ScalingViewport photoView = new()
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            MinSize = new(450, 450),
            SetSize = new(450, 450),
            ViewportSize = new(450, 450),
            MouseFilter = MouseFilterMode.Ignore,
            Eye = eye
        };
        ImageContainer.AddChild(photoView);

        // theres no event raising after full pvs load, so just wait for one sec until everything is loaded
        await Task.Delay(TimeSpan.FromSeconds(1f));

        photoView.Screenshot(TakeScreenshot);
    }

    private void TakeScreenshot(SixLabors.ImageSharp.Image<Rgba32> image)
    {
        TextureRect texture = new()
        {
            VerticalExpand = true,
            HorizontalExpand = true,
            MinSize = new(450, 450),
            Stretch = TextureRect.StretchMode.KeepAspectCentered,
            Texture = Texture.LoadFromImage(image)
        };

        ImageContainer.RemoveAllChildren();
        ImageContainer.AddChild(texture);
        ScreenshotTaken?.Invoke();
    }

    protected override DragMode GetDragModeFor(Vector2 relativeMousePos)
    {
        return DragMode.Move;
    }
}

