using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems._GoobCharacter.Tabs;

[GenerateTypedNameReferences]
public sealed partial class KnowledgeTab : Control
{
    public KnowledgeTab()
    {
        RobustXamlLoader.Load(this);
    }
}
