# Just mob base that don't have Pserishable and DiseaseCarrier component so you don't have to copy paste a lot thing
- type: entity
  save: false
  parent:
  - MobBloodstream
  - MobRespirator
  - MobAtmosStandard
  - MobFlammable
  - BaseMobSpecies
  - BaseMobDisgust
  id: BaseMobSpeciesNonPerishable
  abstract: true
  components:
  - type: Absorbable # Goobstation - changelings
  - type: WraithAbsorbable # Goobstation - wraith
  - type: Barotrauma
    damage:
      types:
        Blunt: 0.50 #per second, scales with pressure and other constants.
        Heat: 0.1
  - type: PassiveDamage # Slight passive regen. Assuming one damage type, comes out to about 4 damage a minute.
    splitBehavior: SplitEnsureAllDamagedAndOrganic # Goob
    allowedStates:
     - Alive
    damageCap: 20 #this looks at vital damage, not total damage, ideally it should look at damage/part but i dont care enough to fix it
    damage:
      types:
        Heat: -0.07
      groups:
        Brute: -0.07
  - type: Fingerprint
  - type: Blindable
  # Other
  - type: Temperature
    currentTemperature: 310.15
    specificHeat: 42
  - type: TemperatureDamage
    heatDamageThreshold: 325
    coldDamageThreshold: 260
    coldDamage:
      types:
        Cold: 0.1 #per second, scales with temperature & other constants
    heatDamage:
      types:
        Heat: 1.0 # Goob edit #per second, scales with temperature & other constants
  - type: TemperatureSpeed
    thresholds:
      293: 0.9
      280: 0.8
      260: 0.7
  - type: ThermalRegulator
    metabolismHeat: 800
    radiatedHeat: 100
    implicitHeatRegulation: 500
    sweatHeatRegulation: 2000
    shiveringHeatRegulation: 2000
    normalBodyTemperature: 310.15
    thermalRegulationTemperatureThreshold: 2
  - type: Butcherable
    butcheringType: Spike # TODO human.
    spawned:
      - id: FoodMeat
        amount: 5
  - type: Respirator
    damage:
      types:
        Asphyxiation: 1.0
    damageRecovery:
      types:
        Asphyxiation: -1.0
  - type: FireVisuals
    alternateState: Standing
  # <Goobstation>
  - type: GrabIntent
  - type: Grabbable
  - type: Carriable
  - type: FootprintOwner # Corvax-Next-Footprints
  - type: CPRTraining # Goobstation - Just give to everyone! This ain't MRP.
  #- type: BloodstreamAffectedByMass # Goobstation: port EE height/width sliders. Also, lol at the comment above. # todo marty otherwise folk instadie
  #  power: 0.6
  - type: FlightAffectedByScale # Goobstation: port EE height/width sliders.
  - type: StunVisuals
  - type: ObraDinnBody # Goobstation
  # </Goobstation>
