// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using System.Collections.Generic; // Pirate: loadout
using Content.Client._Pirate.Lobby.UI.Loadouts; // Pirate: loadout
using Content.Shared.Clothing;
using Content.Shared.Preferences;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Player;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility; // Pirate: loadout

namespace Content.Client.Lobby.UI.Loadouts;

[GenerateTypedNameReferences]
public sealed partial class LoadoutGroupContainer : BoxContainer
{
    private readonly LoadoutGroupPrototype _groupProto;
    private const string ClosedGroupMark = "+"; // Pirate: loadout
    private const string OpenedGroupMark = "-"; // Pirate: loadout
    private readonly Dictionary<string, bool> _openedGroups = new(); // Pirate: loadout

    public event Action<ProtoId<LoadoutPrototype>>? OnLoadoutPressed;
    public event Action<ProtoId<LoadoutPrototype>>? OnLoadoutUnpressed;

    public LoadoutGroupContainer(HumanoidCharacterProfile profile, RoleLoadout loadout, LoadoutGroupPrototype groupProto, ICommonSession session, IDependencyCollection collection)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _groupProto = groupProto;

        RefreshLoadouts(profile, loadout, session, collection);
    }

    /// <summary>
    /// Updates button availabilities and buttons.
    /// </summary>
    public void RefreshLoadouts(HumanoidCharacterProfile profile, RoleLoadout loadout, ICommonSession session, IDependencyCollection collection)
    {
        var protoMan = collection.Resolve<IPrototypeManager>();
        var loadoutSystem = collection.Resolve<IEntityManager>().System<LoadoutSystem>();
        RestrictionsContainer.RemoveAllChildren();

        if (_groupProto.MinLimit > 0)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-min-limit", ("count", _groupProto.MinLimit)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        if (_groupProto.MaxLimit > 0)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-max-limit", ("count", _groupProto.MaxLimit)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        if (protoMan.Resolve(loadout.Role, out var roleProto) && roleProto.Points != null && loadout.Points != null)
        {
            RestrictionsContainer.AddChild(new Label()
            {
                Text = Loc.GetString("loadouts-points-limit", ("count", loadout.Points.Value), ("max", roleProto.Points.Value)),
                Margin = new Thickness(5, 0, 5, 5),
            });
        }

        LoadoutsContainer.RemoveAllChildren();

        // Pirate edit start - port frontier subgroups
        // Get all loadout prototypes for this group.
        //var validProtos = _groupProto.Loadouts.Select(id => protoMan.Index(id));
        var allLoadoutIds = _groupProto.GetAllLoadouts(protoMan).Distinct();
        var validProtos = allLoadoutIds
            .Select(id => protoMan.TryIndex(id, out var proto) ? proto : null)
            .Where(proto => proto is not null)
            .Select(proto => proto!);
        // Pirate edit end - port frontier subgroups

        #region Pirate: loadout
        loadout.SelectedLoadouts.TryGetValue(_groupProto.ID, out var selected);
        var selectedIds = selected?.Select(entry => entry.Prototype).ToHashSet() ?? new HashSet<ProtoId<LoadoutPrototype>>();
        var eligible = validProtos
            .Select(proto =>
            {
                var enabled = loadout.IsValid(profile, session, proto.ID, collection, out var reason);
                return (Prototype: proto, Enabled: enabled, Reason: reason);
            })
            .Where(entry => entry.Enabled || selectedIds.Contains(entry.Prototype.ID))
            .OrderBy(entry => loadoutSystem.GetName(entry.Prototype))
            .ToList();

        var iconRows = new GridContainer
        {
            Columns = 8,
            Margin = new Thickness(5, 0, 5, 5),
        };

        foreach (var entry in eligible)
        {
            iconRows.AddChild(CreateLoadoutIcon(entry.Prototype, loadout, loadoutSystem, entry.Enabled, entry.Reason));
        }

        LoadoutsContainer.AddChild(iconRows);
        #endregion
    }

    private ToggleLoadoutButton CreateToggleButton(KeyValuePair<string, List<LoadoutPrototype>> kvp, LoadoutContainer firstElement, SubLoadoutContainer subContainer)
    {
        var toggle = new ToggleLoadoutButton
        {
            Text = ClosedGroupMark
        };

        toggle.Text = subContainer.Visible ? OpenedGroupMark : ClosedGroupMark;
        toggle.Pressed = subContainer.Visible;

        toggle.OnPressed += _ =>
        {
            var willOpen = !subContainer.Visible;
            subContainer.Visible = willOpen;
            toggle.Text = willOpen ? OpenedGroupMark : ClosedGroupMark;
            toggle.Pressed = willOpen;
            _openedGroups[kvp.Key] = willOpen;
        };

        firstElement.AddChild(toggle);
        toggle.SetPositionFirst();
        return toggle;
    }

    private void UpdateSubGroupSelectedInfo(LoadoutContainer loadout, string itemName, BoxContainer subList)
    {
        var countSubSelected = subList.Children
            .OfType<LoadoutContainer>()
            .Count(c => c.Select.Pressed);

        if (countSubSelected > 0)
        {
            loadout.Text = Loc.GetString("loadouts-count-items-in-group", ("item", itemName), ("count", countSubSelected));
        }
    }

    /// <summary>
    /// Creates a UI container for a single Loadout item.
    ///
    /// This method was extracted from RefreshLoadouts because the logic for creating
    /// individual loadout items is used multiple times inside that method, and duplicating
    /// the code made it harder to maintain.
    ///
    /// Logic:
    /// - Checks if the item is currently selected in the loadout.
    /// - Checks if the item is valid for selection (IsValid).
    /// - Creates a LoadoutContainer with the appropriate status (disabled / active).
    /// - Subscribes to button press events to handle selection and deselection.
    /// </summary>
    /// <param name="proto">The loadout item prototype.</param>
    /// <param name="profile">The humanoid character profile.</param>
    /// <param name="loadout">The current role loadout for the user.</param>
    /// <param name="session">The user's session.</param>
    /// <param name="collection">The dependency injection container.</param>
    /// <param name="loadoutSystem">The loadout system instance.</param>
    /// <returns>A fully initialized LoadoutContainer for UI display.</returns>
    private LoadoutContainer CreateLoadoutUI(LoadoutPrototype proto, HumanoidCharacterProfile profile, RoleLoadout loadout, ICommonSession session, IDependencyCollection collection, LoadoutSystem loadoutSystem)
    {
        var selected = loadout.SelectedLoadouts[_groupProto.ID];

        var pressed = selected.Any(e => e.Prototype == proto.ID);

        var enabled = loadout.IsValid(profile, session, proto.ID, collection, out var reason);

        var cont = new LoadoutContainer(proto, !enabled, reason);

        cont.Text = loadoutSystem.GetName(proto);

        cont.Select.Pressed = pressed;

        cont.Select.OnPressed += args =>
        {
            if (args.Button.Pressed)
                OnLoadoutPressed?.Invoke(proto.ID);
            else
                OnLoadoutUnpressed?.Invoke(proto.ID);
        };

        return cont;
    }

    #region Pirate: loadout
    private LoadoutIconButton CreateLoadoutIcon(LoadoutPrototype proto, RoleLoadout loadout, LoadoutSystem loadoutSystem, bool enabled, FormattedMessage? reason)
    {
        loadout.SelectedLoadouts.TryGetValue(_groupProto.ID, out var selected);
        var pressed = selected?.Any(e => e.Prototype == proto.ID) == true;

        var icon = new LoadoutIconButton(proto, loadoutSystem.GetName(proto), reason: reason) // Pirate: loadout
        {
            Disabled = !enabled,
            Pressed = pressed,
        };

        icon.OnPressed += args =>
        {
            if (args.Button.Pressed)
                OnLoadoutPressed?.Invoke(proto.ID);
            else
                OnLoadoutUnpressed?.Invoke(proto.ID);
        };

        return icon;
    }
    #endregion
}
