using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;


namespace Content.Client._Goobstation.CatridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class MuleWranglerUiFragment : BoxContainer
{
    public MuleWranglerUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(MuleWranglerUiState state)
    {
    }
}
