- type: entity
  id: NTRCrateSpesosSmall
  parent: CratePrivateSecure
  name: bonus de spesos
  description: Les temps difficiles exigent des solutions capitalistes.
  components:
  - type: StorageFill
    contents:
      - id: SpaceCash500
        amount: 20 # Why? cuz a whole ass crate for 1 cash stack is wierd

- type: entity
  id: NTRCratePointDisks
  parent: CrateScienceSecure
  name: bonus de disques à points
  description: Progrès, mon ami, progrès.
  components:
  - type: StorageFill
    contents:
      - id: ResearchDisk
        amount: 10 # 10 x 1000 = 10000 points, should be enough for sci, and also, a whole crate for 1 disk is stupid so 10 disks is good

- type: entity
  id: NTRCrateEmergencyMed
  parent: CrateMedicalSecure
  name: Fournitures médicales d'urgence
  description: Pensez à comment vous allez expliquer ça à NT.
  components:
  - type: StorageFill
    contents:
      - id: MedkitBurnFilled
      - id: MedkitToxinFilled
      - id: MedkitOxygenFilled
      - id: MedkitBruteFilled
      - id: MedkitRadiationFilled # its an emergency med crate, not war med crate so no combat medkits

- type: entity
  id: NTRCrateDisablers
  parent: CrateCommandSecure
  name: caisse de désactivateurs
  description: Une caisse avec des désactivateurs. Pourquoi en auriez-vous besoin ?
  components:
  - type: StorageFill
    contents:
      - id: WeaponDisablerSMG # yknow maybe its too good for tier 1, i hope i dont forget about this before doing a pr
      - id: WeaponDisabler
        amount: 3

- type: entity
  id: NTRCrateToolsSmall
  parent: CrateEngineeringSecure
  name: caisse d'outils
  description: Une caisse avec des outils NanoTrasen standard.
  components:
  - type: StorageFill
    contents:
      - id: Wirecutter
      - id: Screwdriver
      - id: Wrench
      - id: Multitool
      - id: NetworkConfigurator
      - id: ClothingBeltUtility
      - id: Crowbar

- type: entity
  id: NTRBoardTelecom
  parent: CrateCommandSecure
  name: caisse de cartes de circuit de serveur télécom
  description: Une caisse contenant 2 cartes de circuit de serveur télécom.
  components:
  - type: StorageFill
    contents:
    - id: TelecomServerCircuitboard
    - id: TelecomServerCircuitboard

- type: entity
  id: NTRBoardHolopad
  parent: CrateCommandSecure
  name: caisse d'holodal
  description: Une caisse contenant 2 cartes de circuit d'holodal.
  components:
  - type: StorageFill
    contents:
    - id: HolopadMachineCircuitboard
    - id: HolopadMachineCircuitboard # what is the point of having 1 holopad?

- type: entity
  id: NTRBoardShuttle
  parent: CrateEngineeringSecure
  name: caisse paquet constructeur de navette
  components:
  - type: StorageFill
    contents:
    - id: ThrusterFlatpack
      amount: 4
    - id: ShuttleConsoleCircuitboard
    - id: GyroscopeFlatpack
