// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.LinkAccount;

[GenerateTypedNameReferences]
public sealed partial class PatronPerksWindow : DefaultWindow
{
    public PatronPerksWindow()
    {
        RobustXamlLoader.Load(this);
    }
}