// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2025 gluesniffler <159397573+gluesniffler@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Goobstation.Client.Shitmed.Choice.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Shitmed.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class SurgeryStepButton : ChoiceControl
{
    public EntityUid Step { get; set; }

    public SurgeryStepButton()
    {
        RobustXamlLoader.Load(this);
    }
}