
using System.Linq;
using System.Numerics;
using Content.Shared._F14.SCPOS;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._F14.SCPOS;

[GenerateTypedNameReferences]
public sealed partial class SCPOSSoftwareDownloadWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SpriteSystem _spriteSystem;

    public event Action<string>? OnDownloadPressed;
    public event Action<string>? OnUninstallPressed;

    private static readonly Color ColorOk = Color.FromHex("#8fd18f");
    private static readonly Color ColorBad = Color.FromHex("#d17d7d");
    private static readonly Color ColorDim = Color.FromHex("#8a8f8a");
    private static readonly Color ColorAccent = Color.FromHex("#4fa8e0");

    public SCPOSSoftwareDownloadWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _spriteSystem = _entManager.System<SpriteSystem>();

        Title = "SCiPnet Software Download Tool";
    }

    public void UpdateState(SCPOSSoftwareStoreState state)
    {
        var usedFrac = state.DiskCapacity <= 0
            ? 0f
            : Math.Clamp(state.DiskUsed / (float) state.DiskCapacity, 0f, 1f);

        DiskUsageBar.Value = usedFrac * 100f;
        DiskUsageBar.Modulate = usedFrac > 0.9f ? ColorBad : ColorAccent;
        DiskUsageLabel.Text = $"{state.DiskUsed} GQ / {state.DiskCapacity} GQ";

        IdStatusLabel.Text = state.InsertedIdName is null
            ? "NO ID CARD INSERTED"
            : $"ID: {state.InsertedIdName.ToUpper()}";
        IdStatusLabel.FontColorOverride = state.InsertedIdName is null ? ColorBad : ColorOk;

        SoftwareList.DisposeAllChildren();

        var allSoftware = _proto.EnumeratePrototypes<SCPOSSoftwarePrototype>()
            .OrderBy(s => s.Core ? 0 : 1)
            .ThenBy(s => s.Name);

        foreach (var software in allSoftware)
        {
            SoftwareList.AddChild(BuildEntryRow(software, state));
        }
    }

    private Control BuildEntryRow(SCPOSSoftwarePrototype software, SCPOSSoftwareStoreState state)
    {
        var installed = state.InstalledSoftware.Contains(software.ID);
        var hasAccess = software.RequiredAccess.Count == 0
            || software.RequiredAccess.Any(t => state.CurrentAccessTags.Contains(t));
        var fitsOnDisk = state.DiskUsed + software.DiskCost <= state.DiskCapacity;

        var root = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4, 6),
            HorizontalExpand = true
        };

        var headerRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        headerRow.AddChild(new TextureRect
        {
            Texture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath(software.Icon))),
            TextureScale = new Vector2(20, 20) / 32f,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 6, 0)
        });

        headerRow.AddChild(new Label
        {
            Text = software.Name,
            FontColorOverride = ColorOk,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center
        });

        headerRow.AddChild(new Label
        {
            Text = $"{software.DiskCost} GQ",
            FontColorOverride = ColorDim,
            Margin = new Thickness(0, 0, 8, 0),
            VerticalAlignment = VAlignment.Center
        });

        if (installed)
        {
            var runningLabel = new PanelContainer
            {
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2f6b2f") },
                Children = { new Label { Text = " INSTALLED ", FontColorOverride = Color.White } }
            };
            headerRow.AddChild(runningLabel);
        }
        else
        {
            var canDownload = hasAccess && fitsOnDisk;

            var dlBtn = new Button
            {
                Text = "Download",
                Disabled = !canDownload,
                StyleClasses = { "OpenBoth" },
                MinWidth = 90
            };
            dlBtn.OnPressed += _ => OnDownloadPressed?.Invoke(software.ID);
            headerRow.AddChild(dlBtn);
        }

        root.AddChild(headerRow);

        root.AddChild(new Label
        {
            Text = software.Description,
            FontColorOverride = ColorDim,
            Margin = new Thickness(26, 2, 0, 0)
        });

        if (!installed && !hasAccess)
        {
            root.AddChild(new Label
            {
                Text = $"✕ Incompatible! Requires: {string.Join(", ", software.RequiredAccess)}",
                FontColorOverride = ColorBad,
                Margin = new Thickness(26, 1, 0, 0)
            });
        }

        if (!installed && !fitsOnDisk)
        {
            root.AddChild(new Label
            {
                Text = "✕ Not enough disk space!",
                FontColorOverride = ColorBad,
                Margin = new Thickness(26, 1, 0, 0)
            });
        }

        root.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat { BackgroundColor = Color.FromHex("#2a3a2a") },
            MinHeight = 1,
            Margin = new Thickness(0, 6, 0, 0)
        });

        return root;
    }
}
