// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared.Access.Systems;
using Content.Shared.Administration;
using Content.Shared.CriminalRecords;
using Content.Shared.Dataset;
using Content.Shared.Random.Helpers;
using Content.Shared.Security;
using Content.Shared.StationRecords;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Utility;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Random;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;
using Content.Shared.StatusIcon;
using Robust.Client.GameObjects;
#region Pirate: records photos
using Content.Client._Pirate.UserInterface.Controls;
using Content.Shared.Customization.Systems;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared._Pirate.Contractors.Prototypes;
using Content.Shared.Preferences;
using Content.Shared.Roles;
using Content.Client.Lobby;
using Content.Client.Sprite;
using Robust.Client.Graphics;
using Robust.Client.Utility;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using System.IO;
using System.Threading.Tasks;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.PixelFormats;
using Robust.Client.Utility;
using Robust.Shared.ContentPack;
using Robust.Shared.Enums;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
#endregion

namespace Content.Client.CriminalRecords;

// TODO: dedupe shitcode from general records theres a lot
[GenerateTypedNameReferences]
public sealed partial class CriminalRecordsConsoleWindow : FancyWindow
{
    private readonly IPlayerManager _player;
    private readonly IPrototypeManager _proto;
    private readonly IRobustRandom _random;
    private readonly AccessReaderSystem _accessReader;
    [Dependency] private readonly IEntityManager _entManager = default!;
    private readonly SpriteSystem _spriteSystem;
    [Dependency] private readonly IResourceManager _resManager = default!; // Pirate: records photos
    private readonly ContentSpriteSystem _contentSpriteSystem; // Pirate: records photos

    public readonly EntityUid Console;

    private static readonly ProtoId<LocalizedDatasetPrototype> ReasonPlaceholders = "CriminalRecordsWantedReasonPlaceholders";

    public Action<uint?>? OnKeySelected;
    public Action<StationRecordFilterType, string>? OnFiltersChanged;
    public Action<SecurityStatus>? OnStatusSelected;
    public Action<uint>? OnCheckStatus;
    public Action<CriminalRecord, bool, bool>? OnHistoryUpdated;
    public Action? OnHistoryClosed;
    public Action<SecurityStatus, string>? OnDialogConfirmed;
    public Action<SecurityStatus>? OnStatusFilterPressed;
    private uint _maxLength;
    private bool _access;
    private uint? _selectedKey;
    private CriminalRecord? _selectedRecord;

    private DialogWindow? _reasonDialog;


    #region Pirate: records photos
    public Action<string>? OnCreateRecord;
    public Action<uint>? OnDeleteRecord;
    public Action<string, string, string, int, Gender>? OnIdentityInfoChanged;
    public Action<string, string>? OnForensicsInfoChanged;
    private EntityUid _portraitDummy = EntityUid.Invalid;
    private uint? _portraitKey;
    private Texture? _portraitTexture;
    private byte[]? _currentPortraitImageData;
    private readonly HashSet<uint> _pendingGeneratedPortraitKeys = new();
    public Func<Task>? OnPrintPhoto;
    public Action? OnUploadPhoto;
    public Action<uint, byte[]>? OnStoreGeneratedPortrait;
    private readonly List<SpeciesPrototype> _species = new();
    private readonly List<NationalityPrototype> _nationalities = new();
    private readonly List<EmployerPrototype> _employers = new();
    private HumanoidCharacterProfile? _recordProfile;
    private bool _suppressIdentityEditorEvents;
    private bool _deleteConfirmationPending;
    private uint? _deleteConfirmationKey;
    private bool _speciesUnset;
    private bool _nationalityUnset;
    private bool _employerUnset;
    private bool _genderUnset;
    private static readonly IReadOnlyDictionary<string, TimeSpan> EmptyPlayTimes = new Dictionary<string, TimeSpan>();
    #endregion

    private StationRecordFilterType _currentFilterType;

    private SecurityStatus _currentCrewListFilter;

    public CriminalRecordsConsoleWindow(EntityUid console, uint maxLength, IPlayerManager playerManager, IPrototypeManager prototypeManager, IRobustRandom robustRandom, AccessReaderSystem accessReader)
    {
        RobustXamlLoader.Load(this);

        Console = console;
        _player = playerManager;
        _proto = prototypeManager;
        _random = robustRandom;
        _accessReader = accessReader;
        IoCManager.InjectDependencies(this);
        _spriteSystem = _entManager.System<SpriteSystem>();
        _contentSpriteSystem = _entManager.System<ContentSpriteSystem>(); // Pirate: records photos

        _maxLength = maxLength;
        _currentFilterType = StationRecordFilterType.Name;

        _currentCrewListFilter = SecurityStatus.None;

        PersonPortraitBackground.Texture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Parallaxes/layer2.png"))); // Pirate: records photos

        OpenCentered();

        foreach (var item in Enum.GetValues<StationRecordFilterType>())
        {
            FilterType.AddItem(GetTypeFilterLocals(item), (int)item);
        }

        foreach (var status in Enum.GetValues<SecurityStatus>())
        {
            AddStatusSelect(status);
        }

        //Populate status to filter crew list
        foreach (var item in Enum.GetValues<SecurityStatus>())
        {
            CrewListFilter.AddItem(GetCrewListFilterLocals(item), (int)item);
        }

        OnClose += () => _reasonDialog?.Close();

        RecordListing.OnItemSelected += args =>
        {
            if (RecordListing[args.ItemIndex].Metadata is not uint cast)
                return;

            OnKeySelected?.Invoke(cast);
        };

        RecordListing.OnItemDeselected += _ =>
        {
            OnKeySelected?.Invoke(null);
        };

        FilterType.OnItemSelected += eventArgs =>
        {
            var type = (StationRecordFilterType)eventArgs.Id;

            if (_currentFilterType != type)
            {
                _currentFilterType = type;
                FilterListingOfRecords(FilterText.Text);
            }
        };

        //Select Status to filter crew
        CrewListFilter.OnItemSelected += eventArgs =>
        {
            var type = (SecurityStatus)eventArgs.Id;

            if (_currentCrewListFilter != type)
            {
                _currentCrewListFilter = type;

                StatusFilterPressed(type);

            }
        };

        FilterText.OnTextEntered += args =>
        {
            FilterListingOfRecords(args.Text);
        };
        #region Pirate: records photos
        FilterText.OnTextChanged += _ =>
        {
            ResetDeleteConfirmation();
            UpdateRecordActionButtons();
        };
        AddRecordButton.OnPressed += _ => CreateRecordFromSearch();
        DeleteRecordButton.OnPressed += _ =>
        {
            if (_selectedKey == null)
                return;

            if (_deleteConfirmationPending && _deleteConfirmationKey == _selectedKey)
            {
                ResetDeleteConfirmation();
                OnDeleteRecord?.Invoke(_selectedKey.Value);
                return;
            }

            _deleteConfirmationPending = true;
            _deleteConfirmationKey = _selectedKey;
            UpdateRecordActionButtons();
        };
        #endregion

        StatusOptionButton.OnItemSelected += args =>
        {
            SetStatus((SecurityStatus)args.Id);
        };

        HistoryButton.OnPressed += _ =>
        {
            if (_selectedRecord is { } record)
                OnHistoryUpdated?.Invoke(record, _access, true);
        };

        #region Pirate: records photos
        PrintPortraitButton.OnPressed += async _ =>
        {
            if (OnPrintPhoto != null)
            {
                try
                {
                    await OnPrintPhoto();
                }
                catch (System.Exception ex)
                {
                    Logger.ErrorS("criminal-records", $"PrintPortraitButton.OnPressed failed while awaiting OnPrintPhoto/BuildPrintPhotoMessage: {ex}"); // Pirate: records photos
                }
            }
        };
        UploadPortraitButton.OnPressed += _ => OnUploadPhoto?.Invoke();
        PopulateGenderOptions();
        RefreshSpeciesOptions();
        PersonPrintsEdit.IsValid = text => text.Length <= _maxLength;
        PersonDnaEdit.IsValid = text => text.Length <= _maxLength;
        SpeciesButton.OnItemSelected += args =>
        {
            if (_suppressIdentityEditorEvents || _recordProfile == null)
                return;

            _speciesUnset = false;
            SpeciesButton.SelectId(args.Id);
            UpdateRecordIdentityProfile(_recordProfile.WithSpecies(_species[args.Id].ID), true);
        };
        NationalityButton.OnItemSelected += args =>
        {
            if (_suppressIdentityEditorEvents || _recordProfile == null)
                return;

            _nationalityUnset = false;
            NationalityButton.SelectId(args.Id);
            UpdateRecordIdentityProfile(_recordProfile.WithNationality(_nationalities[args.Id].ID), true);
        };
        EmployerButton.OnItemSelected += args =>
        {
            if (_suppressIdentityEditorEvents || _recordProfile == null)
                return;

            _employerUnset = false;
            EmployerButton.SelectId(args.Id);
            UpdateRecordIdentityProfile(_recordProfile.WithEmployer(_employers[args.Id].ID), true);
        };
        GenderButton.OnItemSelected += args =>
        {
            if (_suppressIdentityEditorEvents || _recordProfile == null)
                return;

            _genderUnset = false;
            GenderButton.SelectId(args.Id);
            UpdateRecordIdentityProfile(_recordProfile.WithGender((Gender) args.Id), true);
        };
        AgeEdit.OnTextEntered += args => CommitAgeEdit(args.Text);
        AgeEdit.OnFocusExit += args => CommitAgeEdit(args.Text);
        PersonPrintsEdit.OnTextEntered += args => CommitForensicsEdits(args.Text, PersonDnaEdit.Text);
        PersonPrintsEdit.OnFocusExit += args => CommitForensicsEdits(args.Text, PersonDnaEdit.Text);
        PersonDnaEdit.OnTextEntered += args => CommitForensicsEdits(PersonPrintsEdit.Text, args.Text);
        PersonDnaEdit.OnFocusExit += args => CommitForensicsEdits(PersonPrintsEdit.Text, args.Text);
        UpdateRecordActionButtons();
        #endregion
    }

    public void StatusFilterPressed(SecurityStatus statusSelected)
    {
        OnStatusFilterPressed?.Invoke(statusSelected);
    }

    public void UpdateState(CriminalRecordsConsoleState state)
    {
        var previousSelectedKey = _selectedKey; // Pirate: records photos

        if (state.Filter != null)
        {
            if (state.Filter.Type != _currentFilterType)
            {
                _currentFilterType = state.Filter.Type;
            }

            if (state.Filter.Value != FilterText.Text)
            {
                FilterText.Text = state.Filter.Value;
            }
        }

        if (state.FilterStatus != _currentCrewListFilter)
        {
            _currentCrewListFilter = state.FilterStatus;
        }

        _selectedKey = state.SelectedKey;
        if (previousSelectedKey != _selectedKey) // Pirate: records photos
            ResetDeleteConfirmation(); // Pirate: records photos

        FilterType.SelectId((int)_currentFilterType);
        CrewListFilter.SelectId((int)_currentCrewListFilter);
        NoRecords.Visible = state.RecordListing == null || state.RecordListing.Count == 0;
        PopulateRecordListing(state.RecordListing);

        // set up the selected person's record
        var selected = _selectedKey != null;

        PersonContainer.Visible = selected;
        RecordUnselected.Visible = !selected;

        _access = _player.LocalSession?.AttachedEntity is {} player
            && _accessReader.IsAllowed(player, Console);

        // hide access-required editing parts when no access
        var editing = _access && selected;
        StatusOptionButton.Disabled = !editing;
        #region Pirate: records photos
        UpdateRecordActionButtons();
        SpeciesButton.Disabled = !editing;
        NationalityButton.Disabled = !editing;
        EmployerButton.Disabled = !editing;
        GenderButton.Disabled = !editing;
        AgeEdit.Editable = editing;
        PersonPrintsEdit.Editable = editing;
        PersonDnaEdit.Editable = editing;
        PrintPortraitButton.Disabled = !editing;
        UploadPortraitButton.Disabled = !editing;
        #endregion

        if (state is { CriminalRecord: not null, StationRecord: not null })
        {
            #region Pirate: records photos
            PrintPortraitButton.Disabled = !editing || !CanPrintPortrait(state.CriminalRecord);
            if (state.SelectedKey is { } selectedKey)
                PopulateRecordContainer(selectedKey, state.StationRecord, state.CriminalRecord);
            else
                ClearPortraitDisplay();
            #endregion
            OnHistoryUpdated?.Invoke(state.CriminalRecord, _access, false);
            _selectedRecord = state.CriminalRecord;
        }
        else
        {
            _selectedRecord = null;
            OnHistoryClosed?.Invoke();
            #region Pirate: records photos
            ResetDeleteConfirmation();
            _recordProfile = null;
            ClearPortraitDisplay();
            #endregion
        }
    }

    private void PopulateRecordListing(Dictionary<uint, string>? listing)
    {
        if (listing == null)
        {
            RecordListing.Clear();
            return;
        }

        var entries = listing.Select(i => new ItemList.Item(RecordListing)
        {
            Text = i.Value,
            Metadata = i.Key
        }).ToList();
        entries.Sort((a, b) => string.Compare(a.Text, b.Text, StringComparison.Ordinal));
        RecordListing.SetItems(entries, (a,b) => string.Compare(a.Text, b.Text));
    }

    private void PopulateRecordContainer(uint key, GeneralStationRecord stationRecord, CriminalRecord criminalRecord) // Pirate: records photos
    {
        var specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Misc/job_icons.rsi"), "Unknown");
        var na = Loc.GetString("generic-not-available-shorthand");

        #region Pirate: records photos
        UpdatePortraitDisplay(key, criminalRecord, stationRecord.JobPrototype);
        UpdateRecordIdentityProfile(BuildRecordIdentityProfile(stationRecord, criminalRecord), false, stationRecord);
        PersonJobIcon.Texture = null;
        #endregion

        PersonName.Text = stationRecord.Name;
        PersonJob.Text = stationRecord.JobTitle ?? na;

        // Job icon
        if (_proto.TryIndex<JobIconPrototype>(stationRecord.JobIcon, out var proto))
        {
            PersonJobIcon.Texture = _spriteSystem.Frame0(proto.Icon);
        }

        PersonPrintsEdit.Text = stationRecord.Fingerprint ?? string.Empty; // Pirate: records photos
        PersonDnaEdit.Text = stationRecord.DNA ?? string.Empty; // Pirate: records photos

        if (criminalRecord.Status != SecurityStatus.None)
        {
            specifier = new SpriteSpecifier.Rsi(new ResPath("Interface/Misc/security_icons.rsi"),  GetStatusIcon(criminalRecord.Status));
        }
        PersonStatusTX.SetFromSpriteSpecifier(specifier);
        PersonStatusTX.DisplayRect.TextureScale = new Vector2(3f, 3f);

        StatusOptionButton.SelectId((int)criminalRecord.Status);
        if (criminalRecord.Reason is { } reason)
        {

            var message = FormattedMessage.FromMarkupOrThrow(Loc.GetString($"criminal-records-console-{criminalRecord.Status.ToString().ToLower()}-reason"));
            message.AddText($": {reason}");

            WantedReason.SetMessage(message);
            WantedReason.Visible = true;
        }
        else
        {
            WantedReason.Visible = false;
        }
    }

    #region Pirate: records photos
    private void RefreshSpeciesOptions()
    {
        _species.Clear();
        _species.AddRange(_proto.EnumeratePrototypes<SpeciesPrototype>()
            .Where(species => species.RoundStart)
            .OrderBy(species => Loc.GetString(species.Name)));
    }

    private void PopulateGenderOptions()
    {
        GenderButton.Clear();
        GenderButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-male-text"), (int) Gender.Male);
        GenderButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-female-text"), (int) Gender.Female);
        GenderButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-epicene-text"), (int) Gender.Epicene);
        GenderButton.AddItem(Loc.GetString("humanoid-profile-editor-pronouns-neuter-text"), (int) Gender.Neuter);
    }

    private HumanoidCharacterProfile BuildRecordIdentityProfile(GeneralStationRecord stationRecord, CriminalRecord criminalRecord)
    {
        var effectiveSpecies = string.IsNullOrWhiteSpace(stationRecord.Species)
            ? (string) SharedHumanoidAppearanceSystem.DefaultSpecies
            : stationRecord.Species;
        var profile = criminalRecord.PortraitProfileSnapshot != null
            ? new HumanoidCharacterProfile(criminalRecord.PortraitProfileSnapshot)
            : HumanoidCharacterProfile.DefaultWithSpecies(effectiveSpecies);

        return profile
            .WithName(stationRecord.Name)
            .WithSpecies(effectiveSpecies)
            .WithAge(stationRecord.Age)
            .WithGender(stationRecord.Gender)
            .WithNationality(stationRecord.Nationality)
            .WithEmployer(stationRecord.Employer);
    }

    private void UpdateRecordIdentityProfile(HumanoidCharacterProfile profile, bool sendUpdate, GeneralStationRecord? rawRecord = null)
    {
        profile = NormalizeRecordIdentityProfile(profile);
        _recordProfile = profile;

        if (rawRecord != null)
        {
            _speciesUnset = IsIdentitySelectorBlank(rawRecord.Species);
            _nationalityUnset = IsIdentitySelectorBlank(rawRecord.Nationality);
            _employerUnset = IsIdentitySelectorBlank(rawRecord.Employer);
            _genderUnset = IsIdentitySelectorBlank(rawRecord.Species);
        }

        _suppressIdentityEditorEvents = true;
        try
        {
            PopulateSpeciesSelector(profile.Species, _speciesUnset);
            PopulateNationalitySelector(profile, _nationalityUnset);
            PopulateEmployerSelector(profile, _employerUnset);

            if (_genderUnset)
                ApplyOptionButtonPlaceholder(GenderButton, Loc.GetString("generic-not-available-shorthand"));
            else
                GenderButton.SelectId((int) profile.Gender);

            AgeEdit.Text = rawRecord != null && rawRecord.Age <= 0
                ? string.Empty
                : profile.Age.ToString();
        }
        finally
        {
            _suppressIdentityEditorEvents = false;
        }

        if (sendUpdate)
            SendIdentityUpdate(profile);
    }

    private void PopulateSpeciesSelector(string selectedSpecies, bool showPlaceholder)
    {
        SpeciesButton.Clear();

        for (var i = 0; i < _species.Count; i++)
        {
            SpeciesButton.AddItem(Loc.GetString(_species[i].Name), i);
            if (_species[i].ID == selectedSpecies)
                SpeciesButton.SelectId(i);
        }

        if (showPlaceholder)
            ApplyOptionButtonPlaceholder(SpeciesButton, Loc.GetString("generic-not-available-shorthand"));
    }

    private void PopulateNationalitySelector(HumanoidCharacterProfile profile, bool showPlaceholder)
    {
        NationalityButton.Clear();
        _nationalities.Clear();
        _nationalities.AddRange(GetAvailableNationalities(profile));

        for (var i = 0; i < _nationalities.Count; i++)
        {
            NationalityButton.AddItem(Loc.GetString(_nationalities[i].NameKey), i);
            if (_nationalities[i].ID == profile.Nationality)
                NationalityButton.SelectId(i);
        }

        if (showPlaceholder)
            ApplyOptionButtonPlaceholder(NationalityButton, Loc.GetString("generic-not-available-shorthand"));
    }

    private void PopulateEmployerSelector(HumanoidCharacterProfile profile, bool showPlaceholder)
    {
        EmployerButton.Clear();
        _employers.Clear();
        _employers.AddRange(GetAvailableEmployers(profile));

        for (var i = 0; i < _employers.Count; i++)
        {
            EmployerButton.AddItem(Loc.GetString(_employers[i].NameKey), i);
            if (_employers[i].ID == profile.Employer)
                EmployerButton.SelectId(i);
        }

        if (showPlaceholder)
            ApplyOptionButtonPlaceholder(EmployerButton, Loc.GetString("generic-not-available-shorthand"));
    }

    private HumanoidCharacterProfile NormalizeRecordIdentityProfile(HumanoidCharacterProfile profile)
    {
        if (!_proto.TryIndex<SpeciesPrototype>(profile.Species, out var speciesProto) || !speciesProto.RoundStart)
        {
            profile = profile.WithSpecies(SharedHumanoidAppearanceSystem.DefaultSpecies);
            speciesProto = _proto.Index<SpeciesPrototype>(SharedHumanoidAppearanceSystem.DefaultSpecies);
        }

        profile = profile.WithAge(Math.Clamp(profile.Age, speciesProto.MinAge, speciesProto.MaxAge));

        var nationalities = GetAvailableNationalities(profile);
        if (!string.IsNullOrWhiteSpace(profile.Nationality)
            && !nationalities.Any(nationality => nationality.ID == profile.Nationality))
        {
            var nationality = nationalities.FirstOrDefault(item => item.ID == SharedHumanoidAppearanceSystem.DefaultNationality)
                ?? nationalities.FirstOrDefault();
            if (nationality != null)
                profile = profile.WithNationality(nationality.ID);
        }

        var employers = GetAvailableEmployers(profile);
        if (!string.IsNullOrWhiteSpace(profile.Employer)
            && !employers.Any(employer => employer.ID == profile.Employer))
        {
            var employer = employers.FirstOrDefault(item => item.ID == SharedHumanoidAppearanceSystem.DefaultEmployer)
                ?? employers.FirstOrDefault();
            if (employer != null)
                profile = profile.WithEmployer(employer.ID);
        }

        return profile;
    }

    private List<NationalityPrototype> GetAvailableNationalities(HumanoidCharacterProfile profile)
    {
        return _proto.EnumeratePrototypes<NationalityPrototype>()
            .Where(nationality => RequirementsMet(nationality.Requirements, profile.WithNationality(nationality.ID)))
            .OrderBy(nationality => Loc.GetString(nationality.NameKey))
            .ToList();
    }

    private List<EmployerPrototype> GetAvailableEmployers(HumanoidCharacterProfile profile)
    {
        return _proto.EnumeratePrototypes<EmployerPrototype>()
            .Where(employer => RequirementsMet(employer.Requirements, profile.WithEmployer(employer.ID)))
            .OrderBy(employer => Loc.GetString(employer.NameKey))
            .ToList();
    }

    private bool RequirementsMet(IReadOnlyCollection<JobRequirement>? requirements, HumanoidCharacterProfile profile)
    {
        if (requirements == null || requirements.Count == 0)
            return true;

        foreach (var requirement in requirements)
        {
            if (!requirement.Check(_entManager, _proto, profile, EmptyPlayTimes, out _))
                return false;
        }

        return true;
    }

    private void CommitAgeEdit(string text)
    {
        if (_suppressIdentityEditorEvents || _recordProfile == null)
            return;

        if (!int.TryParse(text, out var age))
        {
            UpdateRecordIdentityProfile(_recordProfile, false);
            return;
        }

        UpdateRecordIdentityProfile(_recordProfile.WithAge(age), true);
    }

    private void CommitForensicsEdits(string fingerprint, string dna)
    {
        if (_suppressIdentityEditorEvents || _selectedKey == null)
            return;

        OnForensicsInfoChanged?.Invoke(fingerprint, dna);
    }

    private void SendIdentityUpdate(HumanoidCharacterProfile profile)
    {
        OnIdentityInfoChanged?.Invoke(
            profile.Species,
            profile.Nationality,
            profile.Employer,
            profile.Age,
            profile.Gender);
    }

    private static bool IsIdentitySelectorBlank(string? value)
    {
        return value != null && string.IsNullOrWhiteSpace(value);
    }

    // Pirate: records photos
    private static void ApplyOptionButtonPlaceholder(OptionButton button, string placeholder)
    {
        OptionButtonHelpers.SetPlaceholder(button, placeholder);
    }
    protected override void Dispose(bool disposing)
    {
        if (disposing)
            ClearPortraitDisplay();

        base.Dispose(disposing);
    }

    public async Task<CriminalRecordPrintPhoto?> BuildPrintPhotoMessage()
    {
        if (_selectedKey is not { } recordKey)
            return null;

        if (!CanPrintPortrait(_selectedRecord))
            return null;

        if (_currentPortraitImageData is { Length: > 0 } currentPortrait &&
            CanLoadPortraitTexture(recordKey, currentPortrait))
            return new CriminalRecordPrintPhoto(recordKey, currentPortrait);

        var selectedRecord = _selectedRecord;
        if (selectedRecord?.PortraitImageData is { Length: > 0 } storedPortrait &&
            CanLoadPortraitTexture(recordKey, storedPortrait))
            return new CriminalRecordPrintPhoto(recordKey, storedPortrait);

        var portraitDummy = _portraitDummy;
        var generatedImageData = await TryGeneratePortraitSnapshotImageDataWithRetry(portraitDummy);
        if (generatedImageData is not { Length: > 0 })
            return new CriminalRecordPrintPhoto(recordKey);

        return new CriminalRecordPrintPhoto(recordKey, generatedImageData);
    }

    private void UpdatePortraitDisplay(uint recordKey, CriminalRecord criminalRecord, string? jobPrototype)
    {
        if (criminalRecord.PortraitImageData is { Length: > 0 } imageData)
        {
            ClearPortraitPreview();
            SetPortraitTexture(recordKey, imageData);

            if (_currentPortraitImageData is { Length: > 0 })
                return;
        }

        ClearPortraitTexture();
        UpdatePortraitPreview(recordKey, criminalRecord.PortraitProfileSnapshot, jobPrototype);
        EnsureGeneratedPortraitImage(recordKey, criminalRecord.PortraitProfileSnapshot, jobPrototype);
    }

    private void UpdatePortraitPreview(uint recordKey, HumanoidCharacterProfile? profileSnapshot, string? jobPrototype)
    {
        if (profileSnapshot == null)
        {
            ClearPortraitPreview();
            PersonPortraitBackground.Visible = true;
            return;
        }

        if (_portraitKey == recordKey && _entManager.EntityExists(_portraitDummy))
            return;

        ClearPortraitPreview();

        if (!TryCreatePortraitDummy(profileSnapshot, jobPrototype, out var portraitDummy))
            return;

        _portraitDummy = portraitDummy;
        PersonPortrait.SetEntity(_portraitDummy);
        PersonPortraitBackground.Visible = true;
        PersonPortrait.Visible = true;
        _portraitKey = recordKey;
    }

    private bool TryCreatePortraitDummy(HumanoidCharacterProfile? profileSnapshot, string? jobPrototype, out EntityUid portraitDummy)
    {
        portraitDummy = EntityUid.Invalid;
        if (profileSnapshot == null)
            return false;

        JobPrototype? job = null;
        if (!string.IsNullOrWhiteSpace(jobPrototype) && _proto.TryIndex<JobPrototype>(jobPrototype, out var indexedJob))
            job = indexedJob;

        portraitDummy = UserInterfaceManager.GetUIController<LobbyUIController>()
            .LoadProfileEntity(profileSnapshot, job, true);
        return portraitDummy != EntityUid.Invalid && _entManager.EntityExists(portraitDummy);
    }

    private void ClearPortraitPreview()
    {
        if (_portraitDummy != EntityUid.Invalid && _entManager.EntityExists(_portraitDummy))
            _entManager.DeleteEntity(_portraitDummy);

        _portraitDummy = EntityUid.Invalid;
        _portraitKey = null;
        PersonPortrait.SetEntity((EntityUid?) null);
        PersonPortrait.Visible = false;
    }

    private void SetPortraitTexture(uint recordKey, byte[] imageData)
    {
        ClearPortraitTexture();

        try
        {
            using var stream = new MemoryStream(imageData, writable: false);
            _portraitTexture = Texture.LoadFromPNGStream(stream, GetPortraitTextureCacheKey(recordKey, imageData));
            PersonPortraitTexture.Texture = _portraitTexture;
            PersonPortraitTexture.Visible = true;
            PersonPortraitBackground.Visible = true;
            PersonPortrait.Visible = false;
            _currentPortraitImageData = [.. imageData];
        }
        catch (Exception)
        {
            ClearPortraitTexture();
            PersonPortrait.Visible = true;
        }
    }

    private void ClearPortraitTexture()
    {
        _portraitTexture = null;
        _currentPortraitImageData = null;
        PersonPortraitTexture.Texture = null;
        PersonPortraitTexture.Visible = false;
    }

    private void ClearPortraitDisplay()
    {
        ClearPortraitPreview();
        ClearPortraitTexture();
        PersonPortraitBackground.Visible = false;
    }

    private static bool CanPrintPortrait(CriminalRecord? criminalRecord)
    {
        return criminalRecord?.PortraitImageData is { Length: > 0 }
            || criminalRecord?.PortraitProfileSnapshot != null;
    }

    private async Task<byte[]?> TryGeneratePortraitSnapshotImageData(EntityUid portraitDummy)
    {
        if (portraitDummy == EntityUid.Invalid || !_entManager.EntityExists(portraitDummy))
            return null;

        if (!_entManager.TryGetComponent<MetaDataComponent>(portraitDummy, out var metadata))
            return null;

        var filePath = ContentSpriteSystem.Exports / $"{metadata.EntityName}-{Direction.South}-{portraitDummy}.png";

        try
        {
            await _contentSpriteSystem.Export(portraitDummy, Direction.South, includeId: true);

            if (!_resManager.UserData.Exists(filePath))
                return null;

            await using var file = _resManager.UserData.Open(filePath, FileMode.Open, FileAccess.Read, FileShare.ReadWrite);
            using var imageData = new MemoryStream();
            await file.CopyToAsync(imageData);
            return imageData.ToArray(); // Pirate: records photos
        }
        catch (Exception)
        {
            return null;
        }
    }

    private async Task<byte[]?> TryGeneratePortraitSnapshotImageDataWithRetry(EntityUid portraitDummy, int attempts = 4, int delayMs = 100)
    {
        for (var attempt = 0; attempt < attempts; attempt++)
        {
            var generatedImageData = await TryGeneratePortraitSnapshotImageData(portraitDummy);
            if (generatedImageData is { Length: > 0 })
                return generatedImageData;

            if (attempt < attempts - 1)
                await Task.Delay(delayMs);
        }

        return null;
    }

    private bool CanLoadPortraitTexture(uint recordKey, byte[] imageData)
    {
        try
        {
            using var stream = new MemoryStream(imageData, writable: false);
            _ = Texture.LoadFromPNGStream(stream, GetPortraitTextureCacheKey(recordKey, imageData));
            return true;
        }
        catch (Exception)
        {
            return false;
        }
    }

    private byte[] NormalizeGeneratedPortraitImageData(byte[] imageData)
    {
        try
        {
            using var stream = new MemoryStream(imageData, writable: false);
            using var image = Image.Load<Rgba32>(stream);
            var sourcePixels = image.GetPixelSpan();
            if (!TryFindOpaqueBounds(sourcePixels, image.Width, image.Height, out var minX, out var minY, out var maxX, out var maxY))
                return imageData;

            const int canvasSize = 250;
            const int padding = 0;
            var cropWidth = maxX - minX + 1;
            var cropHeight = maxY - minY + 1;
            var availableSize = canvasSize - padding * 2;
            var scale = Math.Min((float) availableSize / cropWidth, (float) availableSize / cropHeight);

            if (!float.IsFinite(scale) || scale <= 0f)
                return imageData;

            var drawWidth = Math.Max(1, (int) MathF.Round(cropWidth * scale));
            var drawHeight = Math.Max(1, (int) MathF.Round(cropHeight * scale));
            var offsetX = (canvasSize - drawWidth) / 2;
            var offsetY = (canvasSize - drawHeight) / 2;

            using var output = new Image<Rgba32>(canvasSize, canvasSize);
            var outputPixels = output.GetPixelSpan();
            outputPixels.Clear();

            for (var y = 0; y < drawHeight; y++)
            {
                var sourceY = minY + Math.Min(cropHeight - 1, (int) (y / scale));
                var outputRow = (offsetY + y) * canvasSize;
                var sourceRow = sourceY * image.Width;

                for (var x = 0; x < drawWidth; x++)
                {
                    var sourceX = minX + Math.Min(cropWidth - 1, (int) (x / scale));
                    outputPixels[outputRow + offsetX + x] = sourcePixels[sourceRow + sourceX];
                }
            }

            using var outputStream = new MemoryStream();
            output.SaveAsPng(outputStream);
            return outputStream.ToArray();
        }
        catch (Exception)
        {
            return imageData;
        }
    }

    private static bool TryFindOpaqueBounds(ReadOnlySpan<Rgba32> pixels, int width, int height, out int minX, out int minY, out int maxX, out int maxY)
    {
        minX = width;
        minY = height;
        maxX = -1;
        maxY = -1;

        for (var y = 0; y < height; y++)
        {
            var rowOffset = y * width;
            for (var x = 0; x < width; x++)
            {
                if (pixels[rowOffset + x].A == 0)
                    continue;

                if (x < minX)
                    minX = x;
                if (y < minY)
                    minY = y;
                if (x > maxX)
                    maxX = x;
                if (y > maxY)
                    maxY = y;
            }
        }

        return maxX >= minX && maxY >= minY;
    }

    private string GetPortraitTextureCacheKey(uint recordKey, byte[] imageData)
    {
        var signature = 17;
        for (var i = 0; i < imageData.Length; i++)
        {
            signature = unchecked(signature * 31 + imageData[i]);
        }

        return $"criminal-record-portrait-{recordKey}-{imageData.Length}-{signature}";
    }

    private void EnsureGeneratedPortraitImage(uint recordKey, HumanoidCharacterProfile? profileSnapshot, string? jobPrototype)
    {
        if (profileSnapshot == null ||
            !_pendingGeneratedPortraitKeys.Add(recordKey))
        {
            return;
        }

        if (!TryCreatePortraitDummy(profileSnapshot, jobPrototype, out var portraitDummy))
        {
            _pendingGeneratedPortraitKeys.Remove(recordKey);
            return;
        }

        _ = GenerateAndStorePortraitImageAsync(recordKey, portraitDummy);
    }

    private async Task GenerateAndStorePortraitImageAsync(uint recordKey, EntityUid portraitDummy)
    {
        try
        {
            var generatedImageData = await TryGeneratePortraitSnapshotImageDataWithRetry(portraitDummy);
            if (generatedImageData is not { Length: > 0 } || Disposed)
                return;

            if (_selectedKey == recordKey)
                SetPortraitTexture(recordKey, generatedImageData);

            OnStoreGeneratedPortrait?.Invoke(recordKey, generatedImageData);
        }
        finally
        {
            if (portraitDummy != EntityUid.Invalid && _entManager.EntityExists(portraitDummy))
                _entManager.DeleteEntity(portraitDummy);

            _pendingGeneratedPortraitKeys.Remove(recordKey);
        }
    }
    private void UpdateRecordActionButtons()
    {
        if (_deleteConfirmationKey != _selectedKey)
            ResetDeleteConfirmation();

        AddRecordButton.Disabled = !_access || string.IsNullOrWhiteSpace(SanitizeRecordName(FilterText.Text)); // Pirate: records photos
        DeleteRecordButton.Disabled = !_access || _selectedKey == null;
        // Pirate: records photos
        DeleteRecordButton.ToolTip = _deleteConfirmationPending
            ? Loc.GetString("criminal-records-console-confirm-delete")
            : Loc.GetString("criminal-records-console-delete-record");

        if (_deleteConfirmationPending)
        {
            if (!DeleteRecordButton.StyleClasses.Contains("ButtonColorRed"))
                DeleteRecordButton.StyleClasses.Add("ButtonColorRed");
        }
        else
        {
            DeleteRecordButton.StyleClasses.Remove("ButtonColorRed");
        }
    }

    private void CreateRecordFromSearch()
    {
        // Pirate: records photos
        var name = SanitizeRecordName(FilterText.Text);
        if (name.Length == 0)
            return;

        ResetDeleteConfirmation();
        OnCreateRecord?.Invoke(name);
    }

    private string SanitizeRecordName(string text)
    {
        var sanitized = text.Trim();
        if (sanitized.Length > _maxLength)
            sanitized = sanitized[..(int) _maxLength];

        return sanitized;
    }

    private void ResetDeleteConfirmation()
    {
        _deleteConfirmationPending = false;
        _deleteConfirmationKey = null;
    }
    #endregion

    private void AddStatusSelect(SecurityStatus status)
    {
        var name = Loc.GetString($"criminal-records-status-{status.ToString().ToLower()}");
        StatusOptionButton.AddItem(name, (int)status);
    }

    private void FilterListingOfRecords(string text = "")
    {
        OnFiltersChanged?.Invoke(_currentFilterType, text);
    }

    private void SetStatus(SecurityStatus status)
    {
        if (status == SecurityStatus.Wanted
            || status == SecurityStatus.Suspected
            || status == SecurityStatus.Hostile
            || status == SecurityStatus.Search // Goobstation
            || status == SecurityStatus.Dangerous // Goobstation
            || status == SecurityStatus.Demote) // Goobstation
        {
            GetReason(status);
            return;
        }

        OnStatusSelected?.Invoke(status);
    }

    private void GetReason(SecurityStatus status)
    {
        if (_reasonDialog != null)
        {
            _reasonDialog.MoveToFront();
            return;
        }

        var field = "reason";
        var title = Loc.GetString("criminal-records-status-" + status.ToString().ToLower());
        var placeholders = _proto.Index(ReasonPlaceholders);
        var placeholder = Loc.GetString("criminal-records-console-reason-placeholder", ("placeholder", _random.Pick(placeholders))); // just funny it doesn't actually get used
        var prompt = Loc.GetString("criminal-records-console-reason");
        var entry = new QuickDialogEntry(field, QuickDialogEntryType.LongText, prompt, placeholder);
        var entries = new List<QuickDialogEntry>() { entry };
        _reasonDialog = new DialogWindow(title, entries);

        _reasonDialog.OnConfirmed += responses =>
        {
            var reason = responses[field];
            if (reason.Length < 1 || reason.Length > _maxLength)
                return;

            OnDialogConfirmed?.Invoke(status, reason);
        };

        _reasonDialog.OnClose += () => { _reasonDialog = null; };
    }
    private string GetStatusIcon(SecurityStatus status)
    {
        return status switch
        {
            SecurityStatus.Paroled => "hud_paroled",
            SecurityStatus.Wanted => "hud_wanted",
            SecurityStatus.Detained => "hud_incarcerated",
            SecurityStatus.Discharged => "hud_discharged",
            SecurityStatus.Suspected => "hud_suspected",
            SecurityStatus.Hostile => "hud_hostile",
            SecurityStatus.Eliminated => "hud_eliminated",
            SecurityStatus.Search => "hud_search", // Goobstation
            SecurityStatus.Perma => "hud_perma",  // Goobstation
            SecurityStatus.Dangerous => "hud_dangerous",// Goobstation
            SecurityStatus.Demote => "hud_demote", // Goobstation
            _ => "SecurityIconNone"
        };
    }
    private string GetTypeFilterLocals(StationRecordFilterType type)
    {
        return Loc.GetString($"criminal-records-{type.ToString().ToLower()}-filter");
    }

    private string GetCrewListFilterLocals(SecurityStatus type)
    {
        string result;

        // If "NONE" override to "show all"
        if (type == SecurityStatus.None)
        {
            result = Loc.GetString("criminal-records-console-show-all");
        }
        else
        {
            result = Loc.GetString($"criminal-records-status-{type.ToString().ToLower()}");
        }

        return result;
    }
}
