// SPDX-FileCopyrightText: 2019 Remie Richards <remierichards@gmail.com>
// SPDX-FileCopyrightText: 2019 moneyl <8206401+Moneyl@users.noreply.github.com>
// SPDX-FileCopyrightText: 2020 Exp <theexp111@gmail.com>
// SPDX-FileCopyrightText: 2020 PrPleGoo <felix.leeuwen@gmail.com>
// SPDX-FileCopyrightText: 2020 Víctor Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
// SPDX-FileCopyrightText: 2020 ike709 <ike709@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 20kdc <asdd2808@gmail.com>
// SPDX-FileCopyrightText: 2021 Acruid <shatter66@gmail.com>
// SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Galactic Chimp <63882831+GalacticChimp@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2021 Vera Aguilera Puerto <gradientvera@outlook.com>
// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Ygg01 <y.laughing.man.y@gmail.com>
// SPDX-FileCopyrightText: 2021 mirrorcult <notzombiedude@gmail.com>
// SPDX-FileCopyrightText: 2022 0x6273 <0x40@keemail.me>
// SPDX-FileCopyrightText: 2022 Alex Evgrashin <aevgrashin@yandex.ru>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 metalgearsloth <comedian_vs_clown@hotmail.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Leon Friedrich <60421075+ElectroJr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 AWF <you@example.com>
// SPDX-FileCopyrightText: 2024 Brandon Li <48413902+aspiringLich@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 GitHubUser53123 <110841413+GitHubUser53123@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Guillaume E <262623+quatre@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Kevin Zheng <kevinz5000@gmail.com>
// SPDX-FileCopyrightText: 2024 Kira Bridgeton <161087999+Verbalase@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Tayrtahn <tayrtahn@gmail.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Content.Shared.Administration; // Pirate: chem recipes
using Content.Shared.Storage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using Robust.Client.Audio;

namespace Content.Client.Chemistry.UI
{
    /// <summary>
    /// Client-side UI used to control a <see cref="ReagentDispenserComponent"/>.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class ReagentDispenserWindow : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;
        public event Action<ItemStorageLocation>? OnDispenseReagentButtonPressed;
        public event Action<ItemStorageLocation>? OnEjectJugButtonPressed;
        public event Action? OnToggleValveButtonPressed; // Pirate: chem plumbing

        #region Pirate: chem recipes
        private AudioSystem _audioSystem = default!;
        private DialogWindow? _saveRecipeDialog;
        private bool _isRecordingRecipe;
        private bool? _recordButtonIsCancel;
        public event Action? OnStartRecipeRecordingPressed;
        public event Action? OnCancelRecipeRecordingPressed;
        public event Action<string>? OnSaveRecipePressed;
        public event Action? OnClearRecipesPressed;
        public event Action<string>? OnDispenseRecipePressed;
        public event Action<string>? OnDeleteRecipePressed;
        public event Action<string>? OnSaveRecipeToDiskPressed;
        public event Action<string>? OnCopyDiskRecipePressed;
        public event Action<string>? OnDispenseDiskRecipePressed;
        public event Action<string>? OnDeleteDiskRecipePressed;
        public event Action? OnEjectRecipeDiskPressed;
        #endregion
        /// <summary>
        /// Create and initialize the dispenser UI client-side. Creates the basic layout,
        /// actual data isn't filled in until the server sends data about the dispenser.
        /// </summary>
        public ReagentDispenserWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            ValveButton.OnPressed += _ => OnToggleValveButtonPressed?.Invoke(); // Pirate: chem plumbing
            #region Pirate: chem recipes
            _audioSystem = _entityManager.System<AudioSystem>();

            RecordRecipeButton.OnPressed += _ =>
            {
                ReagentDispenserRecipeUiHelper.PlayRecipeUiClickSound(_audioSystem);
                if (_isRecordingRecipe)
                    OnCancelRecipeRecordingPressed?.Invoke();
                else
                    OnStartRecipeRecordingPressed?.Invoke();
            };
            SaveRecipeButton.OnPressed += _ =>
            {
                ReagentDispenserRecipeUiHelper.PlayRecipeUiClickSound(_audioSystem);
                ReagentDispenserRecipeUiHelper.OpenSaveRecipeDialog(_saveRecipeDialog, SharedReagentDispenser.RecipeNameMaxLength, OnSaveRecipePressed, dialog => _saveRecipeDialog = dialog);
            };
            ClearRecipesButton.OnPressed += _ =>
            {
                ReagentDispenserRecipeUiHelper.PlayRecipeUiClickSound(_audioSystem);
                OnClearRecipesPressed?.Invoke();
            };
            EjectRecipeDiskButton.OnPressed += _ =>
            {
                ReagentDispenserRecipeUiHelper.PlayRecipeUiClickSound(_audioSystem);
                OnEjectRecipeDiskPressed?.Invoke();
            };

            ReagentDispenserRecipeUiHelper.ConfigureRecipeActionButton(RecordRecipeButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-record.svg.192dpi.png");
            ReagentDispenserRecipeUiHelper.ConfigureRecipeActionButton(SaveRecipeButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-save.svg.192dpi.png");
            ReagentDispenserRecipeUiHelper.ConfigureRecipeActionButton(ClearRecipesButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-delete-all.svg.192dpi.png");
            ReagentDispenserRecipeUiHelper.ConfigureRecipeActionButton(EjectRecipeDiskButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-eject.svg.192dpi.png");
            RecipeList.OnResized += () => ReagentDispenserRecipeUiHelper.ApplyRecipeChipWidths(RecipeList);
            RecipeDiskList.OnResized += () => ReagentDispenserRecipeUiHelper.ApplyRecipeChipWidths(RecipeDiskList);
            OnClose += () => _saveRecipeDialog?.Close();
            #endregion
        }

        /// <summary>
        /// Update the button grid of reagents which can be dispensed.
        /// </summary>
        /// <param name="inventory">Reagents which can be dispensed by this dispenser</param>
        public void UpdateReagentsList(List<ReagentInventoryItem> inventory)
        {
            if (ReagentList == null)
                return;

            ReagentList.Children.Clear();
            //Sort inventory by reagentLabel
            inventory.Sort((x, y) => x.ReagentLabel.CompareTo(y.ReagentLabel));

            foreach (var item in inventory)
            {
                var card = new ReagentCardControl(item);
                card.OnPressed += OnDispenseReagentButtonPressed;
                card.OnEjectButtonPressed += OnEjectJugButtonPressed;
                ReagentList.Children.Add(card);
            }
        }

        /// <summary>
        /// Update the UI state when new state data is received from the server.
        /// </summary>
        /// <param name="state">State data sent by the server.</param>
        public void UpdateState(BoundUserInterfaceState state)
        {
            var castState = (ReagentDispenserBoundUserInterfaceState) state;
            UpdateContainerInfo(castState);
            UpdateReagentsList(castState.Inventory);
            UpdateRecipes(castState); // Pirate: chem recipes

            _entityManager.TryGetEntity(castState.OutputContainerEntity, out var outputContainerEnt);
            View.SetEntity(outputContainerEnt);

            // Disable the Clear & Eject button if no beaker
            ClearButton.Disabled = castState.OutputContainer is null;
            EjectButton.Disabled = castState.OutputContainer is null;

            ValveButton.Text = GetValveText(castState.ValveOpen); // Pirate: chem plumbing

            AmountGrid.Selected = ((int)castState.SelectedDispenseAmount).ToString();
        }

        /// <summary>
        /// Update the fill state and list of reagents held by the current reagent container, if applicable.
        /// <para>Also highlights a reagent if it's dispense button is being mouse hovered.</para>
        /// </summary>
        /// <param name="state">State data for the dispenser.</param>
        /// or null if no button is being hovered.</param>
        public void UpdateContainerInfo(ReagentDispenserBoundUserInterfaceState state)
        {
            ContainerInfo.Children.Clear();

            #region Pirate: chem recipes
            if (state.IsRecordingRecipe)
            {
                ContainerInfoName.Text = Loc.GetString("reagent-dispenser-window-recipes-virtual-container-name");
                ContainerInfoFill.Text = $"{ReagentDispenserRecipeUiHelper.GetRecordingTotalVolume(state.RecordingRecipeReagents)}u";
                ReagentDispenserRecipeUiHelper.UpdateVirtualRecordingContents(_prototypeManager, ContainerInfo, state.RecordingRecipeReagents);
                return;
            }
            #endregion

            if (state.OutputContainer is null)
            {
                ContainerInfoName.Text = "";
                ContainerInfoFill.Text = "";
                ContainerInfo.Children.Add(new Label { Text = Loc.GetString("reagent-dispenser-window-no-container-loaded-text") });
                return;
            }

            // Set Name of the container and its fill status (Ex: 44/100u)
            ContainerInfoName.Text = state.OutputContainer.DisplayName;
            ContainerInfoFill.Text = state.OutputContainer.CurrentVolume + "/" + state.OutputContainer.MaxVolume;

            foreach (var (reagent, quantity) in state.OutputContainer.Reagents!)
            {
                // Try get to the prototype for the given reagent. This gives us its name.
                var localizedName = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? p)
                    ? p.LocalizedName
                    : Loc.GetString("reagent-dispenser-window-reagent-name-not-found-text");

                var nameLabel = new Label { Text = $"{localizedName}: " };
                var quantityLabel = new Label
                {
                    Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", quantity)),
                    StyleClasses = { StyleNano.StyleClassLabelSecondaryColor },
                };

                ContainerInfo.Children.Add(new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        nameLabel,
                        quantityLabel,
                    }
                });
            }
        }

        #region Pirate: chem recipes
        private void UpdateRecipes(ReagentDispenserBoundUserInterfaceState state)
        {
            _isRecordingRecipe = state.IsRecordingRecipe;
            var recipeState = new ReagentDispenserRecipeUiHelper.RecipeUiState(
                state.IsRecordingRecipe,
                state.RecordingRecipeReagents,
                state.SavedRecipes,
                state.HasRecipeDisk,
                state.DiskRecipes);
            var callbacks = new ReagentDispenserRecipeUiHelper.RecipeUiCallbacks(
                OnDispenseRecipePressed,
                OnSaveRecipeToDiskPressed,
                OnDeleteRecipePressed,
                OnDispenseDiskRecipePressed,
                OnCopyDiskRecipePressed,
                OnDeleteDiskRecipePressed);
            ReagentDispenserRecipeUiHelper.UpdateRecipeSection(
                recipeState,
                callbacks,
                RecordRecipeButton,
                SaveRecipeButton,
                ClearRecipesButton,
                EjectRecipeDiskButton,
                RecipeDiskSection,
                RecipeList,
                RecipeDiskList,
                ref _recordButtonIsCancel);
        }
        #endregion

        #region Pirate: chem plumbing
        private static string GetValveText(bool open)
        {
            return $"{Loc.GetString("gas-canister-window-valve-label")} {Loc.GetString(open ? "gas-canister-window-valve-open-text" : "gas-canister-window-valve-closed-text")}";
        }
        #endregion
    }
}



