// SPDX-FileCopyrightText: 2025 RichardBlonski <48651647+RichardBlonski@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Goobstation.Client.Antagonists.Abductor.Abductee;

[GenerateTypedNameReferences]
public sealed partial class AbducteeReturnPopup : FancyWindow
{
    private float _remainingTime;

    public AbducteeReturnPopup()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        CloseButton.Visible = false;

        InitializeUI();
        InitializeEvents();
        ResetTimer();
    }

    private void InitializeUI()
    {
        TitleLabel.Text = Loc.GetString("abductee-return-popup-title");

        MessageLabel.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("abductee-return-popup-message")));

        OkButton.Disabled = true;

        UpdateCloseButtonText();
    }

    private void InitializeEvents()
    {
        OkButton.OnPressed += OnClosePressed;
    }

    private void ResetTimer()
    {
        _remainingTime = (float)TimeSpan.FromSeconds(7f).TotalSeconds; // Set how long to show the popup for
        UpdateCloseButtonText();
    }

    private void OnClosePressed(BaseButton.ButtonEventArgs args)
    {
        Close();
    }

    private void UpdateCloseButtonText()
    {
        var isWaiting = _remainingTime > 0f;
        OkButton.Text = isWaiting
            ? Loc.GetString("abductee-return-popup-button-timer", ("time", (int)MathF.Ceiling(_remainingTime)))
            : Loc.GetString("abductee-return-popup-button");
        OkButton.Disabled = isWaiting;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!OkButton.Disabled)
            return;

        _remainingTime = MathF.Max(0f, _remainingTime - args.DeltaSeconds);
        UpdateCloseButtonText();
    }
}

