using Content.Client.UserInterface.Controls;
using Content.Shared._Goobstation.Radio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Goobstation.Radio.UI;

[GenerateTypedNameReferences]
public sealed partial class HandheldRadioMenu : FancyWindow
{

    public event Action<bool>? OnMicPressed;
    public event Action<bool>? OnSpeakerPressed;

    public HandheldRadioMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        MicButton.OnPressed += args => OnMicPressed?.Invoke(args.Button.Pressed);
        SpeakerButton.OnPressed += args => OnSpeakerPressed?.Invoke(args.Button.Pressed);
    }

    public void Update(HandheldRadioBoundUIState state)
    {
        MicButton.Pressed = state.MicEnabled;
        SpeakerButton.Pressed = state.SpeakerEnabled;
    }
}
