// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using Content.Client.Stylesheets;
#region DOWNSTREAM-TPirates: ghost follow menu update
using Content.Client._Pirate.UserInterface.Systems.Ghost.Controls;
#endregion
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Widgets;

[GenerateTypedNameReferences]
public sealed partial class GhostGui : UIWidget
{
    #region DOWNSTREAM-TPirates: ghost follow menu update
    public GhostTargetWindowGoob TargetWindow { get; }
    #endregion

    public event Action? RequestWarpsPressed;
    public event Action? ReturnToBodyPressed;
    public event Action? GhostRolesPressed;
    public event Action? ThunderdomePressed; // Goobstation - Thunderdome
    public event Action? RespawnToLobbyPressed; // Pirate
    private int _prevNumberRoles;

    public GhostGui()
    {
        RobustXamlLoader.Load(this);

        TargetWindow = new GhostTargetWindowGoob(); // DOWNSTREAM-TPirates: ghost follow menu update

        MouseFilter = MouseFilterMode.Ignore;

        GhostWarpButton.OnPressed += _ => RequestWarpsPressed?.Invoke();
        ReturnToBodyButton.OnPressed += _ => ReturnToBodyPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesPressed?.Invoke();
        GhostRolesButton.OnPressed += _ => GhostRolesButton.StyleClasses.Remove(StyleClass.Negative);
        ThunderdomeButton.OnPressed += _ => ThunderdomePressed?.Invoke(); // Goobstation - Thunderdome
        ReturnToRoundButton.OnPressed += _ => RespawnToLobbyPressed?.Invoke(); // PIRATE
        ReturnToRoundButton.Disabled = true; // PIRATE
        ReturnToRoundButton.Visible = false; // PIRATE
    }

    public void Hide()
    {
        TargetWindow.Close();
        Visible = false;
    }

    // Ghoob edit
    public void Update(int? roles, bool? canReturnToBody, bool? canTakeGhostRoles = true)
    {
        ReturnToBodyButton.Disabled = !canReturnToBody ?? true;
        // Goobstation start
        GhostRolesButton.Disabled = !canTakeGhostRoles ?? true;
        // Goobstation end

        if (roles != null)
        {
            GhostRolesButton.Text = Loc.GetString("ghost-gui-ghost-roles-button", ("count", roles));

            if (roles > _prevNumberRoles)
            {
                GhostRolesButton.StyleClasses.Add(StyleClass.Negative);
            }

            _prevNumberRoles = (int)roles;
        }

        TargetWindow.Populate();
    }

    // Goobstation - Thunderdome
    public void UpdateThunderdome(int playerCount)
    {
        ThunderdomeButton.Text = Loc.GetString("thunderdome-ghost-button", ("count", playerCount));
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (disposing)
        {
            TargetWindow.Dispose();
        }
    }

    #region PIRATE
    public void UpdatePirateRespawn(bool hasStatus, bool canRespawn, TimeSpan remainingTime)
    {
        if (!hasStatus)
        {
            ReturnToRoundButton.Visible = false;
            ReturnToRoundButton.Disabled = true;
            ReturnToRoundButton.Text = Loc.GetString("ghost-gui-return-to-round-button");
            return;
        }

        ReturnToRoundButton.Visible = true;

        if (canRespawn)
        {
            ReturnToRoundButton.Disabled = false;
            ReturnToRoundButton.Text = Loc.GetString("ghost-gui-return-to-round-button");
            return;
        }

        ReturnToRoundButton.Disabled = true;

        if (remainingTime.TotalSeconds >= 60)
        {
            var minutesLeft = Math.Max(1, (int) Math.Ceiling(remainingTime.TotalMinutes));
            ReturnToRoundButton.Text = Loc.GetString("ghost-respawn-minutes-left", ("time", minutesLeft));
            return;
        }

        var secondsLeft = Math.Max(1, (int) Math.Ceiling(remainingTime.TotalSeconds));
        ReturnToRoundButton.Text = Loc.GetString("ghost-respawn-seconds-left", ("time", secondsLeft));
    }
    #endregion
}
