# SPDX-FileCopyrightText: 2020 20kdc <asdd2808@gmail.com>
# SPDX-FileCopyrightText: 2020 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 Exp <theexp111@gmail.com>
# SPDX-FileCopyrightText: 2020 Metal Gear Sloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 2020 Paul Ritter <ritter.paul1@googlemail.com>
# SPDX-FileCopyrightText: 2020 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
# SPDX-FileCopyrightText: 2020 V�ctor Aguilera Puerto <6766154+Zumorica@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 V�ctor Aguilera Puerto <zddm@outlook.es>
# SPDX-FileCopyrightText: 2020 peptron1 <57651027+peptron1@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 py01 <60152240+collinlunn@users.noreply.github.com>
# SPDX-FileCopyrightText: 2020 py01 <pyronetics01@gmail.com>
# SPDX-FileCopyrightText: 2021 Fishfish458 <47410468+Fishfish458@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Mith-randalf <84274729+Mith-randalf@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 Swept <sweptwastaken@protonmail.com>
# SPDX-FileCopyrightText: 2021 ZeroDayDaemon <60460608+ZeroDayDaemon@users.noreply.github.com>
# SPDX-FileCopyrightText: 2021 fishfish458 <fishfish458>
# SPDX-FileCopyrightText: 2022 ElectroJr <leonsfriedrich@gmail.com>
# SPDX-FileCopyrightText: 2022 Kara <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2022 Lamrr <96937466+Lamrr@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 Peptide90 <78795277+Peptide90@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 T-Stalker <43253663+DogZeroX@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 T-Stalker <le0nel_1van@hotmail.com>
# SPDX-FileCopyrightText: 2022 Veritius <veritiusgaming@gmail.com>
# SPDX-FileCopyrightText: 2022 ike709 <ike709@github.com>
# SPDX-FileCopyrightText: 2022 ike709 <ike709@users.noreply.github.com>
# SPDX-FileCopyrightText: 2022 metalgearsloth <metalgearsloth@gmail.com>
# SPDX-FileCopyrightText: 2023 Puro <103608145+PuroSlavKing@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 Whisper <121047731+QuietlyWhisper@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
# SPDX-FileCopyrightText: 2023 potato1234_x <79580518+potato1234x@users.noreply.github.com>
# SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: MIT

- type: entity
  name: boîte de menottes
  parent: BoxCardboard
  id: BoxHandcuff
  description: Une boîte pleine de menottes.
  components:
  - type: StorageFill
    contents:
    - id: Handcuffs
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: handcuff

- type: entity
  name: boîte de serflex
  parent: BoxCardboard
  id: BoxZiptie
  description: Une boîte pleine de serflex.
  components:
  - type: StorageFill
    contents:
    - id: Zipties
      amount: 9
  - type: Sprite
    layers:
    - state: box_security
    - state: ziptie

- type: entity
  name: boîte de grenades aveuglantes
  parent: BoxCardboard
  id: BoxFlashbang
  description: 'WARNING: These devices are extremely dangerous and can cause blindness or deafness in repeated use.'
  components:
  - type: StorageFill
    contents:
    - id: GrenadeFlashBang
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: boîte de grenades stinger
  parent: BoxCardboard
  id: BoxStinger
  description: Une boîte pleine de grenades stinger. Dispersez-vous !
  components:
  - type: StorageFill
    contents:
    - id: GrenadeStinger
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: boîte de grenades lacrymogènes
  parent: BoxCardboard
  id: BoxTearGas
  description: Une boîte pleine de grenades lacrymogènes. Retenez votre souffle.
  components:
  - type: StorageFill
    contents:
    - id: TearGasGrenade
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: flashbang

- type: entity
  name: boîte de visières de sécurité
  parent: BoxCardboard
  id: BoxSechud
  description: Une boîte de visières de sécurité.
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesHudSecurity
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: sechud

- type: entity
  name: boîte de lunettes de sécurité
  parent: BoxCardboard
  id: BoxSecglasses
  description: Une boîte de lunettes de sécurité.
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesSecurity
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: secglasses

- type: entity
  name: boîte de lunettes de soleil
  parent: BoxCardboard
  id: BoxSunglasses
  description: Une boîte de lunettes de soleil résistantes aux flashs.
  components:
  - type: StorageFill
    contents:
    - id: ClothingEyesGlassesSunglasses
      amount: 4
  - type: Sprite
    layers:
    - state: box_security
    - state: sunglasses

- type: entity
  name: boîte de tampons médico-légaux
  parent: BoxCardboard
  id: BoxForensicPad
  description: Une boîte de tampons médico-légaux.
  components:
  - type: Item
    shape:
    - 0,0,1,1
  - type: StorageFill
    contents:
    - id: ForensicPad
      amount: 9
  - type: Sprite
    layers:
    - state: box_security
    - state: forensic
