using Content.Client.UserInterface.Controls;
using Content.Shared.Elevator;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Goobstation.Client.Elevator.UI;

[GenerateTypedNameReferences]
public sealed partial class ElevatorMenu : FancyWindow
{
    public event Action<int>? OnFloorPressed;

    public ElevatorMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateFloors(ElevatorBuiState state)
    {
        FloorList.DisposeAllChildren();

        foreach (var floor in state.Floors)
        {
            var id = floor.Item1;
            var name = floor.Item2;

            var btn = new Button
            {
                Text = name,
                Disabled = id == state.CurrentFloor
            };

            btn.OnPressed += _ => OnFloorPressed?.Invoke(id);
            FloorList.AddChild(btn);
        }
    }
}
