// SPDX-FileCopyrightText: 2025 Tyranex <bobthezombie4@gmail.com>
// SPDX-FileCopyrightText: 2025 Goob-Station
//
// SPDX-License-Identifier: MIT

using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.MalfAI;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.MalfAI;

public sealed partial class MalfAiBorgsWindow : FancyWindow
{
    private readonly MalfAiBorgsBoundUserInterface _bui;

    private BoxContainer? _borgList;
    private Label? _noBorgs;
    private Button? _masterLawsetButton;

    public MalfAiBorgsWindow(MalfAiBorgsBoundUserInterface bui)
    {
        _bui = bui;
        RobustXamlLoader.Load(this);
        SetupControls();
    }

    private void SetupControls()
    {
        _borgList = FindControl<BoxContainer>("BorgList");
        _noBorgs = FindControl<Label>("NoBorgs");
        _masterLawsetButton = FindControl<Button>("MasterLawsetButton");

        if (_masterLawsetButton != null)
            _masterLawsetButton.OnPressed += _ => _bui.SendOpenMasterLawset();
    }

    public void UpdateState(MalfAiBorgsUiState state)
    {
        if (_borgList == null)
            return;

        _borgList.RemoveAllChildren();

        if (state.Borgs.Count == 0)
        {
            if (_noBorgs != null)
                _noBorgs.Visible = true;
            return;
        }

        if (_noBorgs != null)
            _noBorgs.Visible = false;

        foreach (var entry in state.Borgs)
        {
            var borgRow = CreateBorgRow(entry);
            _borgList.AddChild(borgRow);
        }
    }

    private Control CreateBorgRow(MalfAiBorgListEntry entry)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 2),
        };

        // Health indicator
        var healthBar = new ProgressBar
        {
            MinValue = 0f,
            MaxValue = 1f,
            Value = entry.HealthFraction,
            MinWidth = 60,
            MaxWidth = 60,
        };

        // Apply color based on health
        if (entry.HealthFraction > 0.6f)
            healthBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Green };
        else if (entry.HealthFraction > 0.3f)
            healthBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Yellow };
        else
            healthBar.ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.Red };

        // Name label
        var nameLabel = new Label
        {
            Text = entry.Name,
            HorizontalExpand = true,
            Margin = new Thickness(4, 0),
        };

        // Sync checkbox
        var syncCheck = new CheckBox
        {
            Text = Loc.GetString("malfai-borgs-sync-label"),
            Pressed = entry.IsSynced,
        };
        syncCheck.OnToggled += args => _bui.SendSetSync(entry.Borg, args.Pressed);

        // Jump button
        var jumpButton = new Button
        {
            Text = Loc.GetString("malfai-borgs-jump-label"),
        };
        jumpButton.OnPressed += _ => _bui.SendJumpToBorg(entry.Borg);

        container.AddChild(healthBar);
        container.AddChild(nameLabel);
        container.AddChild(syncCheck);
        container.AddChild(jumpButton);

        return container;
    }
}
