using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Utility;

namespace Content.Client._Lavaland.GPS.UI;

[GenerateTypedNameReferences]
public sealed partial class GpsItem : BoxContainer
{
    [Dependency] private readonly SpriteSystem _sprite = default!;

    public GpsItem(string name, (Vector2i, string) coordinates, RsiDirection arrowDirection)
    {
        RobustXamlLoader.Load(this);

        NameLabel.Text = name;

        CoordsLabel.Text = $"{coordinates.Item1.X}, {coordinates.Item1.Y}, {coordinates.Item2}";

        var state = _sprite.GetState(new SpriteSpecifier.Rsi(new ResPath("/_Lavaland/Interface/gps.rsi"), "arrow"));
        ArrowPointer.Texture = state.GetFrame(arrowDirection, 0);
        ArrowPointer.TextureScale = new Vector2(0.5f, 0.5f); // tiny
    }
}
