// SPDX-FileCopyrightText: 2022 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2023 Riggle <27156122+RigglePrime@users.noreply.github.com>
//
// SPDX-License-Identifier: MIT
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.Notes;

[GenerateTypedNameReferences]
public sealed partial class AdminNotesWindow : FancyWindow
{
    public AdminNotesWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetTitlePlayer(string playerName)
    {
        Title = Loc.GetString("admin-notes-title", ("player", playerName));
    }
}