// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Goobstation.Shared.Administration.Objectives;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Goobstation.Client.Administration.Objectives;

/// <summary>
/// One objective of the edited mind, with a button to remove it.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class AdminObjectiveRow : PanelContainer
{
    public event Action<NetEntity>? OnRemove;

    public AdminObjectiveRow(AdminObjectiveEntry entry, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        if (entry.Info is { } info)
        {
            IconRect.Texture = sprite.Frame0(info.Icon);
            SetMarkup(TitleLabel, info.Title);
            DescriptionLabel.SetMessage(FormattedMessage.FromUnformatted(info.Description));
            InfoLabel.Text = GetInfoText(entry, info.Progress);
        }
        else
        {
            // GetInfo failed on the server, the objective is broken but can still be removed
            TitleLabel.SetMessage(FormattedMessage.FromUnformatted(Loc.GetString("admin-objectives-invalid", ("proto", entry.ProtoId ?? "?"))));
            DescriptionLabel.Visible = false;
            InfoLabel.Text = entry.Issuer;
        }

        RemoveButton.OnPressed += _ => OnRemove?.Invoke(entry.Objective);
    }

    private static string GetInfoText(AdminObjectiveEntry entry, float progress)
    {
        var text = Loc.GetString("admin-objectives-row-info",
            ("issuer", entry.Issuer),
            ("progress", (int) (progress * 100)),
            ("proto", entry.ProtoId ?? "?"));

        if (entry.TargetName != null)
            text += " | " + Loc.GetString("admin-objectives-row-target", ("target", entry.TargetName));

        return text;
    }

    private static void SetMarkup(RichTextLabel label, string markup)
    {
        // titles use markup, but a broken one must not take the whole window down
        var message = new FormattedMessage();
        message.AddMarkupPermissive(markup);
        label.SetMessage(message);
    }
}
