using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.NTR;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.NTR.UI;

[GenerateTypedNameReferences]
public sealed partial class NtrTaskMenu : FancyWindow
{
    public Action<string>? OnLabelButtonPressed;
    public Action<string>? OnSkipButtonPressed;

    public NtrTaskMenu()
    {
        RobustXamlLoader.Load(this);

        MasterTabContainer.SetTabTitle(0, Loc.GetString("bounty-console-tab-available-label"));
        MasterTabContainer.SetTabTitle(1, Loc.GetString("bounty-console-tab-history-label"));
    }

    /// <summary>
    /// Добавляет задачи в интерфейс
    /// </summary>
    /// <param name="tasks"></param>
    /// <param name="history"></param>
    /// <param name="untilNextSkip"></param>
    public void UpdateEntries(List<NtrTaskData> tasks, List<NtrTaskHistoryData> history, TimeSpan untilNextSkip)
    {
        BountyEntriesContainer.Children.Clear();
        foreach (var t in tasks)
        {
            var entry = new TaskEntry(t, untilNextSkip);
            entry.OnLabelButtonPressed += () => OnLabelButtonPressed?.Invoke(t.Id);
            entry.OnSkipButtonPressed += () => OnSkipButtonPressed?.Invoke(t.Id);

            BountyEntriesContainer.AddChild(entry);
        }
        BountyEntriesContainer.AddChild(new Control
        {
            MinHeight = 10
        });

        BountyHistoryContainer.Children.Clear();
        if (history.Count == 0)
        {
            NoHistoryLabel.Visible = true;
        }
        else
        {
            NoHistoryLabel.Visible = false;

            // Show the history in reverse, so last entry is first in the list
            for (var i = history.Count - 1; i >= 0; i--)
            {
                BountyHistoryContainer.AddChild(new NtrTaskHistoryEntry(history[i]));
            }
        }
    }
}
