- type: entity
  parent: BaseItem
  id: DartMonkeyCube
  name: cube de singe fléchettes
  description: Un cube compressé qui, lorsqu'utilisé, produit un singe stationnaire tirant des fléchettes sur les ballons.
  components: 
  - type: Sprite
    sprite: _Goobstation/Objects/Fun/Monkey_Turrets/dartmonkey.rsi
    state: cube
  - type: Item
    size: Tiny
  - type: SpawnItemsOnUse
    items:
    - id: MonkeyTurretDartBase
      path: /Audio/Effects/unwrap.ogg
   
    
- type: entity
  id: CrateDartMonkey
  parent: CratePlastic
  name: caisse de singe fléchettes
  description: Une caisse contenant un singe fléchettes hautement compressé. Parfait pour crever des ballons — ne questionnez juste pas l'éthique...
  components:
  - type: StorageFill
    contents:
    - id: DartMonkeyCube
      amount: 1
