// SPDX-FileCopyrightText: 2023 CommieFlowers <rasmus.cedergren@hotmail.com>
// SPDX-FileCopyrightText: 2023 rolfero <45628623+rolfero@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 12rabbits <53499656+12rabbits@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Alzore <140123969+Blackern5000@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 ArtisticRoomba <145879011+ArtisticRoomba@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Brandon Hu <103440971+Brandon-Huu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Dimastra <65184747+Dimastra@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Dimastra <dimastra@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Emisse <99158783+Emisse@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Eoin Mcloughlin <helloworld@eoinrul.es>
// SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 JIPDawg <51352440+JIPDawg@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 JIPDawg <JIPDawg93@gmail.com>
// SPDX-FileCopyrightText: 2024 Mervill <mervills.email@gmail.com>
// SPDX-FileCopyrightText: 2024 Moomoobeef <62638182+Moomoobeef@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 PJBot <pieterjan.briers+bot@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers@gmail.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 PopGamer46 <yt1popgamer@gmail.com>
// SPDX-FileCopyrightText: 2024 PursuitInAshes <pursuitinashes@gmail.com>
// SPDX-FileCopyrightText: 2024 QueerNB <176353696+QueerNB@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Saphire Lattice <lattice@saphi.re>
// SPDX-FileCopyrightText: 2024 ShadowCommander <10494922+ShadowCommander@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Simon <63975668+Simyon264@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Spessmann <156740760+Spessmann@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Thomas <87614336+Aeshus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 2024 github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 stellar-novas <stellar_novas@riseup.net>
// SPDX-FileCopyrightText: 2024 themias <89101928+themias@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.UserInterface.CustomControls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Goobstation.Client.DeviceNetwork.UI;

[GenerateTypedNameReferences]
public sealed partial class DeviceCustomFrequencyWindow : DefaultWindow
{
    public uint MinReceiveFrequency;
    public uint MaxReceiveFrequency;
    public uint MinTransmitFrequency;
    public uint MaxTransmitFrequency;

    public event Action<uint>? OnReceiveFrequencyChanged;
    public event Action<uint>? OnTransmitFrequencyChanged;
    public event Action? OnResetToDefault;

    public FloatSpinBox? ReceiveSpin;
    public FloatSpinBox? TransmitSpin;

    public DeviceCustomFrequencyWindow()
    {
        RobustXamlLoader.Load(this);

        ResetToDefaults.OnPressed += _ => OnResetToDefault?.Invoke();
    }

    private void OnReceiveChanged(FloatSpinBox.FloatSpinBoxEventArgs arg)
    {
        var value = (uint) MathF.Round(arg.Value, MidpointRounding.ToZero);
        OnReceiveFrequencyChanged?.Invoke(value);
    }

    private void OnTransmitChanged(FloatSpinBox.FloatSpinBoxEventArgs arg)
    {
        var value = (uint) MathF.Round(arg.Value, MidpointRounding.ToZero);
        OnTransmitFrequencyChanged?.Invoke(value);
    }

    // We are using FloatSpinBox because for some reason only they have an event raised when the value is changed.
    // AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

    /// <summary>
    /// Ensures that receive frequency spinbox exists and sets it to some value.
    /// </summary>
    public void EnsureReceiveSpin(uint frequency)
    {
        if (ReceiveSpin is null)
        {
            ReceiveSpin ??= new FloatSpinBox(1f, 0) { HorizontalExpand = true, MinWidth = 160 };
            ReceiveSpin.IsValid = f => f > MinReceiveFrequency && f < MaxReceiveFrequency;
            ReceiveSpin.OnValueChanged += OnReceiveChanged;

            ReceiveFrequencyContainer.AddChild(new Label { Text = Loc.GetString("ui-device-custom-frequency-receive-label") });
            ReceiveFrequencyContainer.AddChild(ReceiveSpin);
        }


        ReceiveSpin.Value = frequency;
    }

    /// <summary>
    /// Ensures that transmit frequency spinbox exists and sets it to some value.
    /// </summary>
    public void EnsureTransmitSpin(uint frequency)
    {
        if (TransmitSpin is null)
        {
            TransmitSpin = new FloatSpinBox(1f, 0) { HorizontalExpand = true, MinWidth = 160 };
            TransmitSpin.IsValid = f => f > MinTransmitFrequency && f < MaxTransmitFrequency;
            TransmitSpin.OnValueChanged += OnTransmitChanged;

            TransmitFrequencyContainer.AddChild(new Label { Text = Loc.GetString("ui-device-custom-frequency-transmit-label") });
            TransmitFrequencyContainer.AddChild(TransmitSpin);
        }

        TransmitSpin.Value = frequency;
    }
}
