- type: entity
  parent: BaseAction
  id: ActionActivateAutoinjector
  name: Activer l'auto-injecteur
  description: Activez votre auto-injecteur pour administrer des produits chimiques dans votre flux sanguin.
  categories: [ HideSpawnMenu ]
  components:
  - type: Action
    checkCanInteract: false
    checkConsciousness: false
    itemIconStyle: NoItem
    icon:
      sprite: _Goobstation/Actions/modsuit.rsi
      state: stim
    useDelay: 70
  - type: InstantAction
    event: !type:ActionActivateAutoInjectorEvent {}
