using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.Teleportation.Components;
using Robust.Shared.Timing;
using System.Numerics;
using Robust.Client.UserInterface.Controls;

namespace Content.Goobstation.Client.Teleport.Ui;

[GenerateTypedNameReferences]
public sealed partial class TeleSciWindow : FancyWindow
{
    [Dependency] private readonly IGameTiming _timing = default!;

    private Entity<TelesciComputerComponent>? _owner;
    private TelesciState _state;

    public event Action<Vector2>? OnSendButtonPressed;
    public event Action<Vector2>? OnRetrieveButtonPressed;

    //public event Action? OnOpenPortalButtonPressed;

    public TeleSciWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SendButton.OnPressed += Send;
        RetrieveButton.OnPressed += Retrieve;

        PortalButton.Disabled = true;
        PortalButton.ToggleMode = true;
    }

    public TeleSciWindow(EntityUid owner, TelesciComputerComponent computer)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SendButton.OnPressed += Send;
        RetrieveButton.OnPressed += Retrieve;

        PortalButton.Disabled = true;
        PortalButton.ToggleMode = true;

        Update((owner, computer));
    }

    public void Update(Entity<TelesciComputerComponent> ent)
    {
       UpdateState(ent);
       UpdateButton();
       UpdateStatusText();
       SetCordinates(ent);
    }

    private void UpdateState(Entity<TelesciComputerComponent> ent)
    {
        _state = TelesciState.Unknown;

        if (ent.Comp.TeleporterEntity == null)
            _state = TelesciState.NotConnected;
        else
            _state = TelesciState.Ready;

        if(ent.Comp.CooldownTime > _timing.CurTime)
            _state = TelesciState.Cooldown;
    }

    private void UpdateButton()
    {
        switch (_state)
        {
            case TelesciState.NotConnected:
            case TelesciState.Cooldown:
                PortalButton.Disabled = true;
                SendButton.Disabled = true;
                RetrieveButton.Disabled = true;
                break;
            case TelesciState.Ready:
               // PortalButton.Disabled = false;
                SendButton.Disabled = false;
                RetrieveButton.Disabled = false;
                break;
        }
    }

    private void UpdateStatusText()
    {
        var output = "";
        switch (_state)
        {
            case TelesciState.Ready:
                output = Loc.GetString("teleporter-computer-status-ready");
                break;
            case TelesciState.NotConnected:
                output = Loc.GetString("teleporter-computer-status-not-connected");
                break;
            case TelesciState.Cooldown:
                output = Loc.GetString("teleporter-computer-status-cooldown");
                break;
        }
        StatusOutput.Text = output;
    }

    private void SetCordinates(Entity<TelesciComputerComponent> ent)
    {
        XNodeInput.Value = ent.Comp.X;
        YNodeInput.Value = ent.Comp.Y;
    }

    private void Send(BaseButton.ButtonEventArgs obj)
        => OnSendButtonPressed?.Invoke(new Vector2(XNodeInput.Value, YNodeInput.Value));

    private void Retrieve(BaseButton.ButtonEventArgs obj)
        => OnRetrieveButtonPressed?.Invoke(new Vector2(XNodeInput.Value, YNodeInput.Value));

    private enum TelesciState
    {
        Unknown,
        NotConnected,
        Ready,
        Cooldown
    }
}


