// SPDX-FileCopyrightText: 2025 Space Station 14 Contributors
//
// SPDX-License-Identifier: MIT-WIZARDS

﻿using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterWindow : DefaultWindow
{
    public CharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
