// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Shared.Silicons.Laws;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Goobstation.Client.CustomLawboard;

[GenerateTypedNameReferences]
public sealed partial class LawboardSiliconLawContainer : BoxContainer
{
    private SiliconLaw? _law;
    public event Action<SiliconLaw>? MoveLawUp;
    public event Action<SiliconLaw>? MoveLawDown;
    public event Action<SiliconLaw>? DeleteAction;
    public event Action<SiliconLaw>? ChangeLawEvent;


    public LawboardSiliconLawContainer()
    {
        RobustXamlLoader.Load(this);

        MoveUp.OnPressed += _ => MoveLawUp?.Invoke(_law!);
        MoveDown.OnPressed += _ => MoveLawDown?.Invoke(_law!);

        LawContent.OnTextChanged += _ => _law!.LawString = Rope.Collapse(LawContent.TextRope).Trim();
        LawContent.Placeholder = new Rope.Leaf(Loc.GetString("silicon-law-ui-placeholder"));
        Delete.OnPressed += _ => DeleteAction?.Invoke(_law!);
    }

    public void SetLaw(SiliconLaw law)
    {
        _law = law;
        LawNumberLabel.Text = Loc.GetString("laws-ui-law-header", ("id", law.Order));
        LawContent.TextRope = new Rope.Leaf(Loc.GetString(law.LawString));
        LawContent.OnTextChanged += _ => ChangeLawEvent?.Invoke(_law!);
    }
}
