using Content.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Shared.Utility;

namespace Content.Client._Harmony.Objectives;

[GenerateTypedNameReferences]
public sealed partial class BlankObjectiveUi : FancyWindow
{
    public BlankObjectiveUi()
    {
        RobustXamlLoader.Load(this);
    }

    public string GetObjectiveName()
    {
        return ObjectiveNameLineEdit.Text;
    }

    public string GetObjectiveDesc()
    {
        return Rope.Collapse(ObjectiveDescriptionTextEdit.TextRope);
    }
}
