// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Shared._Oskarrr.WorkingJoe;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._Oskarrr.WorkingJoe;

[GenerateTypedNameReferences]
public sealed partial class WorkingJoeVoiceWindow : DefaultWindow
{
    private static readonly string[] QuestionCategories =
    [
        "Curious", "Interrogation", "Identification", "Concern"
    ];

    private const int MaxRecent = 5;
    private readonly WorkingJoeVoiceFavorites _favorites;
    private readonly List<string> _recentIds = new();
    private List<WorkingJoeVoiceLineData> _allLines = new();
    private string? _selectedCategory;
    private bool _showFavorites;

    public WorkingJoeVoiceWindow(WorkingJoeVoiceFavorites favorites)
    {
        _favorites = favorites;
        RobustXamlLoader.Load(this);
        SearchBar.OnTextChanged += _ => RebuildList();
    }

    public event Action<string>? OnLineSelected;

    public void SetLines(List<WorkingJoeVoiceLineData> lines)
    {
        _allLines = lines.OrderBy(l => l.Category).ThenBy(l => l.DisplayName).ToList();
        RebuildCategories();
        RebuildList();
    }

    private void RebuildCategories()
    {
        CategoryList.RemoveAllChildren();

        AddMetaButton("All", () =>
        {
            _selectedCategory = null;
            _showFavorites = false;
        }, _selectedCategory == null && !_showFavorites);

        AddMetaButton("★ Favorites", () =>
        {
            _showFavorites = true;
            _selectedCategory = null;
        }, _showFavorites);

        AddMetaButton("Recent", () =>
        {
            _selectedCategory = "__recent";
            _showFavorites = false;
        }, _selectedCategory == "__recent");

        var nonQuestion = _allLines.Select(l => l.Category).Distinct()
            .Where(c => !QuestionCategories.Contains(c)).OrderBy(c => c).ToList();
        var question = _allLines.Select(l => l.Category).Distinct()
            .Where(c => QuestionCategories.Contains(c))
            .OrderBy(c => Array.IndexOf(QuestionCategories, c)).ToList();

        foreach (var category in nonQuestion)
            AddCategoryButton(category);

        if (question.Count > 0)
        {
            CategoryList.AddChild(new Label
            {
                Text = "Questions",
                FontColorOverride = Color.FromHex("#AAAAAA"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 6, 0, 2)
            });

            foreach (var category in question)
                AddCategoryButton(category);
        }
    }

    private void AddMetaButton(string text, Action onPressed, bool pressed)
    {
        var button = new Button
        {
            Text = text,
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = pressed
        };
        button.OnPressed += _ =>
        {
            onPressed();
            RebuildList();
            RebuildCategories();
        };
        CategoryList.AddChild(button);
    }

    private void AddCategoryButton(string category)
    {
        var button = new Button
        {
            Text = category,
            HorizontalExpand = true,
            ToggleMode = true,
            Pressed = _selectedCategory == category
        };
        button.OnPressed += _ =>
        {
            _selectedCategory = category;
            _showFavorites = false;
            RebuildList();
            RebuildCategories();
        };
        CategoryList.AddChild(button);
    }

    private void RebuildList()
    {
        LineList.RemoveAllChildren();
        var search = SearchBar.Text.Trim().ToLowerInvariant();

        IEnumerable<WorkingJoeVoiceLineData> filtered;
        if (_selectedCategory == "__recent")
        {
            filtered = _recentIds
                .Select(id => _allLines.FirstOrDefault(l => l.LineId == id))
                .Where(l => l != null)!
                .Cast<WorkingJoeVoiceLineData>();
        }
        else if (_showFavorites)
        {
            filtered = _allLines.Where(l => _favorites.Contains(l.LineId));
        }
        else
        {
            filtered = _allLines.Where(l => _selectedCategory == null || l.Category == _selectedCategory);
        }

        var list = filtered
            .Where(l => string.IsNullOrEmpty(search) || l.DisplayName.ToLowerInvariant().Contains(search))
            .ToList();

        foreach (var line in list)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                SeparationOverride = 4
            };

            var isFav = _favorites.Contains(line.LineId);
            var lineId = line.LineId;
            var favButton = new Button
            {
                Text = isFav ? "★" : "☆",
                MinWidth = 30,
                MaxWidth = 30
            };
            favButton.OnPressed += _ =>
            {
                _favorites.Toggle(lineId);
                RebuildList();
            };
            row.AddChild(favButton);

            var lineButton = new Button
            {
                Text = line.DisplayName,
                HorizontalExpand = true
            };
            lineButton.OnPressed += _ =>
            {
                OnLineSelected?.Invoke(lineId);
                AddRecent(lineId);
            };
            row.AddChild(lineButton);
            LineList.AddChild(row);
        }

        if (list.Count == 0)
        {
            LineList.AddChild(new Label
            {
                Text = "No results.",
                FontColorOverride = Color.FromHex("#888888"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 12)
            });
        }
    }

    private void AddRecent(string lineId)
    {
        _recentIds.Remove(lineId);
        _recentIds.Insert(0, lineId);
        if (_recentIds.Count > MaxRecent)
            _recentIds.RemoveAt(_recentIds.Count - 1);
    }
}
