using System.Linq;
using Content.Goobstation.Shared.Gangwars.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Gangwars.Administration;

/// <summary>
/// Admin Panel for the gangwars gamemode.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GangAdminWindow : DefaultWindow
{
    public event Action<Color, Color, string>? OnManualRename;
    public event Action<Color>? OnForceRename;
    public event Action<NetEntity>? OnKick;
    public event Action<NetEntity>? OnSetLeader;
    public event Action<NetEntity, int>? OnSetPoints;
    public event Action<Color, NetEntity>? OnAddMember;

    private List<GangAdminInfo> _gangs = new();
    private List<GangAdminPlayerInfo> _players = new();
    private Color? _selectedColor;
    private NetEntity? _selectedMember;

    private GangCreatorWindow? _renameWindow;
    private GangAdminPointsDialog? _pointsDialog;
    private GangAdminPlayerPickerDialog? _pickerDialog;

    public GangAdminWindow()
    {
        RobustXamlLoader.Load(this);

        ManualRenameButton.OnPressed += _ => OpenManualRename();
        ForceRenameButton.OnPressed += _ =>
        {
            if (_selectedColor is { } color)
                OnForceRename?.Invoke(color);
        };
        KickButton.OnPressed += _ =>
        {
            if (_selectedMember is { } member)
                OnKick?.Invoke(member);
        };
        SetLeaderButton.OnPressed += _ =>
        {
            if (_selectedMember is { } member)
                OnSetLeader?.Invoke(member);
        };
        AddMemberButton.OnPressed += _ => OpenAddMember();

        UpdateButtons();
    }

    public void SetData(List<GangAdminInfo> gangs, List<GangAdminPlayerInfo> players)
    {
        _gangs = gangs;
        _players = players;

        if (_selectedColor is { } selected && _gangs.All(g => g.Color != selected))
            _selectedColor = null;

        RebuildGangList();
        RebuildDetails();
    }

    private void RebuildGangList()
    {
        GangList.RemoveAllChildren();

        foreach (var gang in _gangs)
        {
            var color = gang.Color;
            var entry = new GangAdminGangEntry(gang, _selectedColor == color);
            entry.OnSelected += () =>
            {
                _selectedColor = color;
                ClearMemberSelection();
                RebuildGangList();
                RebuildDetails();
            };
            GangList.AddChild(entry);
        }
    }

    private void RebuildDetails()
    {
        MemberList.RemoveAllChildren();

        if (_selectedColor is not { } color || _gangs.All(g => g.Color != color))
        {
            ClearMemberSelection();
            DetailsTitle.Text = Loc.GetString("gang-admin-no-selection");
            DetailsTitle.FontColorOverride = null;
            UpdateButtons();
            return;
        }

        var gang = _gangs.First(g => g.Color == color);
        DetailsTitle.Text = gang.Name;
        DetailsTitle.FontColorOverride = color;

        if (_selectedMember is { } selectedMember && gang.Members.All(m => m.Entity != selectedMember))
            ClearMemberSelection();

        foreach (var member in gang.Members.OrderByDescending(m => m.IsLeader))
        {
            var entry = new GangAdminMemberEntry(member, _selectedMember == member.Entity);
            entry.OnSelected += () =>
            {
                _selectedMember = member.Entity;
                RebuildDetails();
            };
            entry.OnPointsPressed += () => OpenPointsDialog(member);
            MemberList.AddChild(entry);
        }

        UpdateButtons();
    }

    private void OpenPointsDialog(GangAdminMemberInfo member)
    {
        _pointsDialog?.Close();
        _pointsDialog = new GangAdminPointsDialog(member.Name, member.Points);
        _pointsDialog.OnConfirmed += points => OnSetPoints?.Invoke(member.Entity, points);
        _pointsDialog.OpenCentered();
    }

    private void OpenAddMember()
    {
        if (_selectedColor is not { } color)
            return;

        _pickerDialog?.Close();
        _pickerDialog = new GangAdminPlayerPickerDialog(_players);
        _pickerDialog.OnPicked += player => OnAddMember?.Invoke(color, player);
        _pickerDialog.OpenCentered();
    }

    private void OpenManualRename()
    {
        if (_selectedColor is not { } oldColor || _gangs.All(g => g.Color != oldColor))
            return;

        var gang = _gangs.First(g => g.Color == oldColor);

        _renameWindow?.Close();
        _renameWindow = new GangCreatorWindow(new Dictionary<Color, string>(), oldColor, gang.Name);
        _renameWindow.OnColorPicked += (newColor, name) => OnManualRename?.Invoke(oldColor, newColor, name);
        _renameWindow.OpenCentered();
    }

    private void ClearMemberSelection()
    {
        _selectedMember = null;
    }

    private void UpdateButtons()
    {
        var hasGang = _selectedColor != null;
        var hasMember = _selectedMember != null;

        ManualRenameButton.Disabled = !hasGang;
        ForceRenameButton.Disabled = !hasGang;
        AddMemberButton.Disabled = !hasGang;
        KickButton.Disabled = !hasMember;
        SetLeaderButton.Disabled = !hasMember;
    }
}
