using Content.Goobstation.Shared.Gangwars.Administration;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Gangwars.Administration;

/// <summary>
/// The gang listings.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GangAdminGangEntry : BoxContainer
{
    public event Action? OnSelected;

    public GangAdminGangEntry(GangAdminInfo gang, bool selected)
    {
        RobustXamlLoader.Load(this);

        ColorSwatch.PanelOverride = new StyleBoxFlat { BackgroundColor = gang.Color };
        SelectButton.Text = gang.Name;
        SelectButton.Pressed = selected;
        SelectButton.OnPressed += _ => OnSelected?.Invoke();
    }
}
