// SPDX-FileCopyrightText: 2023 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Piras314 <p1r4s@proton.me>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Administration.UI.BanList;

[GenerateTypedNameReferences]
public sealed partial class BanListWindow : DefaultWindow
{
    public BanListWindow()
    {
        RobustXamlLoader.Load(this);

        TabContainer.SetTabTitle(0, Loc.GetString("ban-list-bans"));
        TabContainer.SetTabTitle(1, Loc.GetString("ban-list-role-bans"));
    }

    public void SetTitlePlayer(string playerName)
    {
        Title = Loc.GetString("ban-list-title", ("player", playerName));
    }
}