using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class SiliconNameMenu : DefaultWindow
    {
        private HumanoidCharacterProfile? _profile;
        public event Action<string>? OnNameChanged;

        public SiliconNameMenu()
        {
            RobustXamlLoader.Load(this);
        }
        public void Initialize(HumanoidProfileEditor humanoid, HumanoidCharacterProfile? profile)
        {
            _profile = profile;

            BorgNameEdit.Text = _profile?.BorgName ?? string.Empty;

            BorgNameEdit.OnTextChanged += args =>
            {
                if (!string.IsNullOrEmpty(args.Text))
                    OnNameChanged?.Invoke(args.Text);
            };

            BorgNameRandomize.OnPressed += args =>
            {
                var randomName = HumanoidCharacterProfile.GetBorgName();
                BorgNameEdit.Text = randomName;
                OnNameChanged?.Invoke(randomName);
            };
        }
    }
}
