using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Phones.UI;

[GenerateTypedNameReferences]
public sealed partial class ChangePhoneName : FancyWindow
{
    public event Action<string>? OnTextChanged;
    public event Action<string>? OnCategoryChanged;
    public ChangePhoneName()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        FillCategories();
        MessageEdit.OnTextChanged += _ => OnTextChanged?.Invoke(MessageEdit.Text);
        CategoryOption.OnItemSelected += args =>
        {
            CategoryOption.SelectId(args.Id);
            string selectedText = "hidden";
            switch (args.Id) // I never found out how to find the label text :godont
            {
                case 0:
                    selectedText = "command";
                    break;
                case 1:
                    selectedText = "security";
                    break;
                case 2:
                    selectedText = "engineering";
                    break;
                case 3:
                    selectedText = "cargo";
                    break;
                case 4:
                    selectedText = "medical";
                    break;
                case 5:
                    selectedText = "science";
                    break;
                case 6:
                    selectedText = "service";
                    break;
                case 7:
                    selectedText = "uncategorized";
                    break;
                case 8:
                    selectedText = "hidden";
                    break;
            }
            OnCategoryChanged?.Invoke(selectedText);
        };
    }

    private void FillCategories()
    {
        CategoryOption.AddItem("command");
        CategoryOption.AddItem("security");
        CategoryOption.AddItem("engineering");
        CategoryOption.AddItem("cargo");
        CategoryOption.AddItem("medical");
        CategoryOption.AddItem("science");
        CategoryOption.AddItem("service");
        CategoryOption.AddItem("uncategorized");
        CategoryOption.AddItem("hidden");
    }
}
