using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.Phones.Components;
using Content.Shared.Speech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Goobstation.Client.Phones.UI;

[GenerateTypedNameReferences]
public sealed partial class PhoneMenu : FancyWindow
{
    [Dependency] private readonly IEntityManager _entitySystem = default!;
    public event Action<int>? OnKeypadButtonPressed;
    public event Action? OnClearButtonPressed;
    public event Action? OnEnterButtonPressed;

    public PhoneMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
        FillKeypadGrid();
    }

    private void FillKeypadGrid()
    {
        // add 3 rows of keypad buttons (1-9)
        for (var i = 1; i <= 9; i++)
        {
            AddKeypadButton(i);
        }

        // clear button
        var clearBtn = new Button()
        {
            Text = "C"
        };
        clearBtn.OnPressed += _ => OnClearButtonPressed?.Invoke();
        KeypadGrid.AddChild(clearBtn);

        // zero button
        AddKeypadButton(0);

        // enter button
        var enterBtn = new Button()
        {
            Text = "D"
        };
        enterBtn.OnPressed += _ => OnEnterButtonPressed?.Invoke();
        KeypadGrid.AddChild(enterBtn);
    }

    public void FillPhoneBook()
    {
        var query = _entitySystem.EntityQueryEnumerator<RotaryPhoneComponent, TransformComponent>();
        while (query.MoveNext(out var phone, out var phoneComp, out var transform))
        {
            if (phoneComp.PhoneNumber == null || phoneComp.Category == null || !_entitySystem.EntityExists(phone))
                return;

            AddPhoneBookLabel(phoneComp.Name ?? "Unknown", phoneComp.Category, phoneComp.PhoneNumber.Value, phone.Id);
        }
    }

    private void AddKeypadButton(int i)
    {
        var btn = new Button()
        {
            Text = i.ToString()
        };

        btn.OnPressed += _ => OnKeypadButtonPressed?.Invoke(i);
        KeypadGrid.AddChild(btn);
    }

    private void AddPhoneBookLabel(string name, string catagory, int phonenumber, int namee)
    {
        var label = new RichTextLabel()
        {
            Text = name + " - " + phonenumber
        };

        switch (catagory)
        {
            case "Command":
                CommandHeading.AddChild(label);
                break;
            case "Security":
                SecurityHeading.AddChild(label);
                break;
            case "Engineering":
                EngineeringHeading.AddChild(label);
                break;
            case "Cargo" or "Supply":
                CargoHeading.AddChild(label);
                break;
            case "Medical":
                MedicalHeading.AddChild(label);
                break;
            case "Science":
                ScienceHeading.AddChild(label);
                break;
            case "Service":
                ServiceHeading.AddChild(label);
                break;
            case "Uncategorized":
                break;
        }
    }
}
