using Robust.Client.UserInterface.XAML;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;

namespace Content.Client.Labels.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class HandRenamerWindow : DefaultWindow
    {
        public event Action<string>? OnNameChanged;
        private bool _focused;
        private string _name = string.Empty;

        public HandRenamerWindow()
        {
            RobustXamlLoader.Load(this);

            NameLineEdit.OnTextChanged += e =>
            {
                _name = e.Text;
                OnNameChanged?.Invoke(_name);
            };
            NameLineEdit.OnFocusEnter += _ => _focused = true;
            NameLineEdit.OnFocusExit += _ =>
            {
                _focused = false;
                NameLineEdit.Text = _name;
            };
            NameLineEdit.GrabKeyboardFocus();
        }

        public void SetCurrentName(string name)
        {
            if (name == _name)
                return;

            _name = name;
            if (!_focused)
                NameLineEdit.Text = name;
        }

        public void SetMaxNameLength(int maxLength)
        {
            NameLineEdit.IsValid = s => s.Length <= maxLength;
        }
    }
}
