using Content.Shared._Goobstation.Contracts;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Goobstation.Contractor
{
    [UsedImplicitly]
    public sealed class ContractorUplinkBoundUserInterface(EntityUid owner, Enum uiKey) : BoundUserInterface(owner, uiKey)
    {
        private ContractorUplink? _uplink;

        protected override void Open()
        {
            base.Open();

            _uplink = this.CreateWindow<ContractorUplink>();
            _uplink.OnContractButtonClicked += ButtonPressed;
        }

        protected override void UpdateState(BoundUserInterfaceState state)
        {
            base.UpdateState(state);

            var castState = (ContractorUplinkBoundUserInterfaceState) state;
            _uplink?.UpdateState(castState); //Update window state
        }

        public void ButtonPressed(UiButton button)
        {
            Logger.Debug("TEST");
            SendMessage(new UiButtonPressedMessage(button));
        }
    }
}
