using Content.Shared._Goobstation.Contracts;
using Content.Shared.IdentityManagement;
using Microsoft.CodeAnalysis.Elfie.Serialization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Serilog;

namespace Content.Client._Goobstation.Contractor;

[GenerateTypedNameReferences]
public sealed partial class ContractorUplink : DefaultWindow
{
    public event Action<UiButton>? OnContractButtonClicked;
    private readonly IEntityManager _entityManager;

    public ContractorUplink()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _entityManager = IoCManager.Resolve<IEntityManager>();
    }

    public void UpdateState(BoundUserInterfaceState state)
    {
        var castState = (ContractorUplinkBoundUserInterfaceState) state;

        Logger.Debug("UpdateState");
        if (ContractContainer.ChildCount > 0)
            ContractContainer.Children.Clear();

        Log.Debug(castState.Tc.ToString());
        // fill out the list of contracts
        foreach (var (target, locations) in castState.Contracts)
        {
            var contractUi = new Contract();
            contractUi.TargetText.Text = Identity.Name(_entityManager.GetEntity(target), _entityManager);
            PopulateLocations(locations, contractUi);
        }
    }

    public void PopulateLocations(List<NetEntity> locations, Contract ui)
    {
        foreach (var location in locations)
        {
            var button = new Button();
            button.Text = Identity.Name(_entityManager.GetEntity(location), _entityManager) + " (x) TC";
            ui.ExtractionOptions.AddChild(button);
            button.OnPressed += _ => OnContractButtonClicked?.Invoke(UiButton.SelectTarget);
        }
    }
}
