// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Goobstation.Client.Observer.Hud;

[GenerateTypedNameReferences]
public sealed partial class ObserverHudPopup : Popup
{
    public event Action<bool, bool, bool>? HudOptionsChanged;

    public ObserverHudPopup()
    {
        RobustXamlLoader.Load(this);

        JobMindshieldCheckBox.OnToggled += OnCheckBoxToggled;
        HealthCheckBox.OnToggled += OnCheckBoxToggled;
        CriminalRecordsCheckBox.OnToggled += OnCheckBoxToggled;
    }

    // Clearing the checkboxes from code does not trigger OnToggled
    public void ClearSelection()
    {
        JobMindshieldCheckBox.Pressed = false;
        HealthCheckBox.Pressed = false;
        CriminalRecordsCheckBox.Pressed = false;
    }

    private void OnCheckBoxToggled(ButtonToggledEventArgs _)
    {
        HudOptionsChanged?.Invoke(
            JobMindshieldCheckBox.Pressed,
            HealthCheckBox.Pressed,
            CriminalRecordsCheckBox.Pressed);
    }
}
