// SPDX-FileCopyrightText: 2024 Brandon Li <48413902+aspiringLich@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 IrisTheAmped <iristheamped@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Goobstation.Shared.Chemistry;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Goobstation.Client.Chemistry.UI;

[GenerateTypedNameReferences]
public sealed partial class EnergyReagentCardControl : Control
{
    public string ReagentId { get; }
    public Action<string>? OnPressed;

    public EnergyReagentCardControl(EnergyReagentInventoryItem item)
    {
        RobustXamlLoader.Load(this);

        ReagentId = item.ReagentId;
        ColorPanel.PanelOverride = new StyleBoxFlat { BackgroundColor = item.ReagentColor };
        ReagentNameLabel.Text = item.ReagentLabel;
        FillLabel.Text = $"{item.PowerCostPerUnit}W/u";

        MainButton.OnPressed += args => OnPressed?.Invoke(ReagentId);
    }
}
