// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Linq;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.Chemistry;
using Content.Shared.Chemistry;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using static Robust.Client.UserInterface.Controls.BoxContainer;

#region Pirate: chem recipes
using Content.Client.Chemistry.UI; 
using Content.Shared.Administration;
using Content.Shared.Storage;
using Robust.Client.Audio;
#endregion

namespace Content.Goobstation.Client.Chemistry.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class EnergyReagentDispenserWindow : FancyWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;
        #region Pirate: chem recipes
        private AudioSystem _audioSystem = default!;
        private DialogWindow? _saveRecipeDialog;
        private bool _isRecordingRecipe;
        private bool? _recordButtonIsCancel;
        #endregion

        private float _batteryCharge;
        private float _batteryMaxCharge;
        private float _currentReceiving;
        private float _idleUse;
        private bool _usingBattery;
        private bool _hasPower;
        private int _selectedAmount;
        private float _lastBatteryCharge = -1;
        private bool _cardsNeedUpdate = true;
        public event Action<string>? OnDispenseReagentButtonPressed;
        public event Action? OnToggleValveButtonPressed; // Pirate: chem plumbing
        #region Pirate: chem recipes
        public event Action? OnStartRecipeRecordingPressed;
        public event Action? OnCancelRecipeRecordingPressed;
        public event Action<string>? OnSaveRecipePressed;
        public event Action? OnClearRecipesPressed;
        public event Action<string>? OnDispenseRecipePressed;
        public event Action<string>? OnDeleteRecipePressed;
        public event Action<string>? OnSaveRecipeToDiskPressed;
        public event Action<string>? OnCopyDiskRecipePressed;
        public event Action<string>? OnDispenseDiskRecipePressed;
        public event Action<string>? OnDeleteDiskRecipePressed;
        public event Action? OnEjectRecipeDiskPressed;
        #endregion
        public EnergyReagentDispenserWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            ValveButton.OnPressed += _ => OnToggleValveButtonPressed?.Invoke(); // Pirate: chem plumbing
            #region Pirate: chem recipes
            _audioSystem = _entityManager.System<AudioSystem>();
            RecordRecipeButton.OnPressed += _ =>
            {
                ReagentDispenserRecipeUiHelper.PlayRecipeUiClickSound(_audioSystem);
                if (_isRecordingRecipe)
                    OnCancelRecipeRecordingPressed?.Invoke();
                else
                    OnStartRecipeRecordingPressed?.Invoke();
            };
            SaveRecipeButton.OnPressed += _ =>
            {
                ReagentDispenserRecipeUiHelper.PlayRecipeUiClickSound(_audioSystem);
                ReagentDispenserRecipeUiHelper.OpenSaveRecipeDialog(_saveRecipeDialog, SharedEnergyReagentDispenser.RecipeNameMaxLength, OnSaveRecipePressed, dialog => _saveRecipeDialog = dialog);
            };
            ClearRecipesButton.OnPressed += _ =>
            {
                ReagentDispenserRecipeUiHelper.PlayRecipeUiClickSound(_audioSystem);
                OnClearRecipesPressed?.Invoke();
            };
            EjectRecipeDiskButton.OnPressed += _ =>
            {
                ReagentDispenserRecipeUiHelper.PlayRecipeUiClickSound(_audioSystem);
                OnEjectRecipeDiskPressed?.Invoke();
            };

            ReagentDispenserRecipeUiHelper.ConfigureRecipeActionButton(RecordRecipeButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-record.svg.192dpi.png");
            ReagentDispenserRecipeUiHelper.ConfigureRecipeActionButton(SaveRecipeButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-save.svg.192dpi.png");
            ReagentDispenserRecipeUiHelper.ConfigureRecipeActionButton(ClearRecipesButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-delete-all.svg.192dpi.png");
            ReagentDispenserRecipeUiHelper.ConfigureRecipeActionButton(EjectRecipeDiskButton, "/Textures/_Pirate/Interface/VerbIcons/ChemRecipes/recipe-eject.svg.192dpi.png");
            RecipeList.OnResized += () => ReagentDispenserRecipeUiHelper.ApplyRecipeChipWidths(RecipeList);
            RecipeDiskList.OnResized += () => ReagentDispenserRecipeUiHelper.ApplyRecipeChipWidths(RecipeDiskList);
            OnClose += () => _saveRecipeDialog?.Close();
            #endregion
        }

        public void UpdateReagentsList(List<EnergyReagentInventoryItem> inventory)
        {
            ReagentList.Children.Clear();
            inventory.Sort((x, y) => string.Compare(x.ReagentLabel, y.ReagentLabel, StringComparison.Ordinal));

            foreach (var card in inventory.Select(item => new EnergyReagentCardControl(item))) // Pirate: chem recipes
            {
                card.OnPressed += OnDispenseReagentButtonPressed;
                ReagentList.Children.Add(card);
            }
            _cardsNeedUpdate = true;
            UpdateCardStates();
        }

        public void UpdateState(BoundUserInterfaceState message)
        {
            if (message is not EnergyReagentDispenserBoundUserInterfaceState state)
                return;

            _batteryMaxCharge = state.BatteryMaxCharge;
            _batteryCharge = state.BatteryCharge;
            _currentReceiving = state.CurrentReceivingEnergy;
            _idleUse = state.IdleUse;
            _selectedAmount = (int) state.SelectedDispenseAmount;
            _usingBattery = state.UsingBattery;
            _hasPower = state.HasPower;

            UpdateContainerInfo(state);
            UpdateReagentsList(state.Inventory);
            UpdateRecipes(state); // Pirate: chem recipes
            UpdateBatteryPercent();

            _entityManager.TryGetEntity(state.OutputContainerEntity, out var outputContainerEnt);
            View.SetEntity(outputContainerEnt);

            ClearButton.Disabled = state.OutputContainer is null;
            EjectButton.Disabled = state.OutputContainer is null;

            ValveButton.Text = GetValveText(state.ValveOpen); // Pirate: chem plumbing

            AmountGrid.Selected = ((int) state.SelectedDispenseAmount).ToString();
            _cardsNeedUpdate = true;
            UpdateCardStates();
        }

        private void UpdateBatteryPercent()
        {
            var batteryPercent = _batteryMaxCharge > 0
                ? _batteryCharge / _batteryMaxCharge * 100
                : 0;

            BatteryStatusLabel.Text = $"{_batteryCharge,3:F0}/{_batteryMaxCharge,3:F0} ({batteryPercent,3:F0}%)";
            BatteryStatusLabel.StyleClasses.Clear();
            BatteryStatusLabel.StyleClasses.Add(batteryPercent switch
            {
                > 60 => "Good",
                > 30 => "Caution",
                _ => "Danger",
            });
        }

        private void UpdateContainerInfo(EnergyReagentDispenserBoundUserInterfaceState state)
        {
            ContainerInfo.Children.Clear();
            #region Pirate: chem recipes
            if (state.IsRecordingRecipe)
            {
                ContainerInfoName.Text = Loc.GetString("reagent-dispenser-window-recipes-virtual-container-name");
                ContainerInfoFill.Text = $"{ReagentDispenserRecipeUiHelper.GetRecordingTotalVolume(state.RecordingRecipeReagents)}u";
                ReagentDispenserRecipeUiHelper.UpdateVirtualRecordingContents(_prototypeManager, ContainerInfo, state.RecordingRecipeReagents);
                return;
            }
            #endregion

            if (state.OutputContainer is null)
            {
                ContainerInfoName.Text = "";
                ContainerInfoFill.Text = "";
                ContainerInfo.Children.Add(new Label { Text = Loc.GetString("reagent-dispenser-window-no-container-loaded-text") });
                return;
            }

            ContainerInfoName.Text = state.OutputContainer.DisplayName;
            ContainerInfoFill.Text = state.OutputContainer.CurrentVolume + "/" + state.OutputContainer.MaxVolume;

            foreach (var (reagent, quantity) in state.OutputContainer.Reagents!)
            {
                var localizedName = _prototypeManager.TryIndex(reagent.Prototype, out ReagentPrototype? proto)
                    ? proto.LocalizedName
                    : Loc.GetString("reagent-dispenser-window-reagent-name-not-found-text");

                var nameLabel = new Label { Text = $"{localizedName}: " };
                var quantityLabel = new Label
                {
                    Text = Loc.GetString("reagent-dispenser-window-quantity-label-text", ("quantity", quantity)),
                    StyleClasses = { StyleClass.LabelWeak }, // Pirate: ui fixes (legacy style migration; prefer upstream on conflict)
                };

                ContainerInfo.Children.Add(new BoxContainer
                {
                    Orientation = LayoutOrientation.Horizontal,
                    Children =
                    {
                        nameLabel,
                        quantityLabel,
                    },
                });
            }
        }

        private void UpdateCardStates()
        {
            if (!_cardsNeedUpdate) // Pirate: chem recipes
                return;

            var stateChanged = false;
            foreach (var child in ReagentList.Children)
            {
                if (child is not EnergyReagentCardControl card)
                    continue;

                var totalCost = card.PowerCostPerUnit * _selectedAmount;
                var shouldBeDisabled = totalCost > _batteryCharge;
                if (card.IsDisabled == shouldBeDisabled)
                    continue;
                stateChanged = true;
                break;
            }

            if (!stateChanged && _lastBatteryCharge == _batteryCharge)
                return;

            _lastBatteryCharge = _batteryCharge;
            _cardsNeedUpdate = false;
            HandleToggle();
        }

        private void HandleToggle()
        {
            foreach (var child in ReagentList.Children)
            {
                if (child is not EnergyReagentCardControl card)
                    continue;

                var totalCost = card.PowerCostPerUnit * _selectedAmount;
                card.SetDisabled(totalCost > _batteryCharge, "Insufficient energy");
            }
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            var oldCharge = _batteryCharge;

            /// Causes the UI to assume the battery is charging if it is connected to APC, and thus not refresh every tick
            /// Refreshing every tick makes the UI extremely hard to use as buttons cannot be pressed at the same time
            /// We check if ApcPowerReceiverBatteryComponent is enabled, aka the machine is using the battery for idle power as APC is off/disconnected
            /// If you touch this expect the indicator to go fucking whack or the UI to become problematic. UI suck moment. This seriously caused issues for so long because braindead
            /// We add a check for if Powered is false because when the battery hits 0, usingBattery becomes false despite no APC power still, otherwise it will start to tick back up the second it hits 0
            if (_usingBattery || !_hasPower)
                _batteryCharge = Math.Clamp(_batteryCharge - _idleUse * args.DeltaSeconds, 0, _batteryMaxCharge);
            else
                _batteryCharge = Math.Clamp(_batteryCharge + _currentReceiving * args.DeltaSeconds, 0, _batteryMaxCharge);

            if ((int) oldCharge != (int) _batteryCharge)
                UpdateBatteryPercent();

            CheckEnergyThresholds(oldCharge, _batteryCharge);
        }

        private void CheckEnergyThresholds(float oldEnergy, float newEnergy)
        {
            foreach (var child in ReagentList.Children)
            {
                if (child is not EnergyReagentCardControl card)
                    continue;

                var threshold = card.PowerCostPerUnit * _selectedAmount;
                if ((!(oldEnergy < threshold) || !(newEnergy >= threshold)) &&
                    (!(oldEnergy >= threshold) || !(newEnergy < threshold)))
                    continue;
                _cardsNeedUpdate = true;
                break;
            }
            UpdateCardStates();
        }
        // Pirate: chem plumbing
        private static string GetValveText(bool open)
        {
            return $"{Loc.GetString("gas-canister-window-valve-label")} {Loc.GetString(open ? "gas-canister-window-valve-open-text" : "gas-canister-window-valve-closed-text")}";
        }

        #region Pirate: chem recipes
        private void UpdateRecipes(EnergyReagentDispenserBoundUserInterfaceState state)
        {
            _isRecordingRecipe = state.IsRecordingRecipe;
            var recipeState = new ReagentDispenserRecipeUiHelper.RecipeUiState(
                state.IsRecordingRecipe,
                state.RecordingRecipeReagents,
                state.SavedRecipes,
                state.HasRecipeDisk,
                state.DiskRecipes);
            var callbacks = new ReagentDispenserRecipeUiHelper.RecipeUiCallbacks(
                OnDispenseRecipePressed,
                OnSaveRecipeToDiskPressed,
                OnDeleteRecipePressed,
                OnDispenseDiskRecipePressed,
                OnCopyDiskRecipePressed,
                OnDeleteDiskRecipePressed);
            ReagentDispenserRecipeUiHelper.UpdateRecipeSection(
                recipeState,
                callbacks,
                RecordRecipeButton,
                SaveRecipeButton,
                ClearRecipesButton,
                EjectRecipeDiskButton,
                RecipeDiskSection,
                RecipeList,
                RecipeDiskList,
                ref _recordButtonIsCancel);
        }
        #endregion
    }
}


