# SPDX-License-Identifier: AGPL-3.0-or-later

- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 10h # Goobstation
      inverted: true # stop playing intern if you're good at science!
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
  guides: [ Science ] # goobstation
  goobcoins: 20 #Goob content
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ResearchAssistantGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket2: BookScientistsGuidebook
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ResearchAssistantChameleonOutfit
  job: ResearchAssistant
  equipment:
    head: ClothingHeadHatCardborg
    eyes: ClothingEyesGlasses
    mask: ClothingMaskGas
    neck: ClothingNeckScarfStripedPurple
    outerClothing: ClothingOuterCoatLab
    gloves: ClothingHandsGlovesLatex
