- type: entity
  id: PrinterDocMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: "друкована плата принтера документів"
  description: "Друкована плата машини для принтера документів"
  components:
    - type: MachineBoard
      prototype: PrinterDoc
      stackRequirements:
        Steel: 3
        Manipulator: 1
        Glass: 1

- type: entity
  id: MassDriverCircuitboard
  parent: BaseMachineCircuitboard
  name: "плата мас-драйвера"
  components:
  - type: MachineBoard
    prototype: MassDriver
    stackRequirements:
      Steel: 5
      Manipulator: 2
      Cable: 4
