// SPDX-FileCopyrightText: 2026 Jonikibaka <153797633+Jonikibaka@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Goobstation.Maths.FixedPoint;
using Content.Shared.Alert;
using Content.Shared.Store;
using Robust.Shared.GameStates;
using Robust.Shared.Prototypes;

namespace Content.Goobstation.Shared.MalfunctionAi;

/// <summary>
/// Added to a station AI once it has been turned into a Malfunction AI antagonist.
/// Tracks malf-only state such as processing power (the store currency for abilities),
/// the number of hacked APCs, and the Doomsday device state.
/// Abilities are bought in a store (uplink-style) for processing power ("CPU").
/// </summary>
[RegisterComponent, NetworkedComponent]
[AutoGenerateComponentState]
public sealed partial class MalfunctionAiComponent : Component
{
    /// <summary>
    /// Mirror of the store CPU balance, networked so the client HUD counter can display it.
    /// The authoritative balance lives in the AI's StoreComponent.
    /// </summary>
    [DataField, ViewVariables(VVAccess.ReadWrite), AutoNetworkedField]
    public FixedPoint2 ProcessingPower;

    /// <summary>
    /// CPU granted to the store when the AI first becomes malfunctioning.
    /// </summary>
    [DataField]
    public FixedPoint2 StartingPower = 50;

    /// <summary>
    /// Hard cap for the CPU balance.
    /// </summary>
    [DataField, ViewVariables(VVAccess.ReadWrite)]
    public FixedPoint2 MaxProcessingPower = 1000;

    /// <summary>
    /// How many unique APCs this AI has hacked. Drives income and gates the Doomsday device purchase.
    /// </summary>
    [DataField, ViewVariables(VVAccess.ReadWrite), AutoNetworkedField]
    public int HackedApcCount;

    /// <summary>
    /// One-time processing power granted per APC hacked.
    /// </summary>
    [DataField]
    public FixedPoint2 CpuPerApc = 10;

    /// <summary>
    /// Continuous income: CPU per second generated by each hacked APC
    /// (tg: +1 per ~2s machine tick per APC — "mining").
    /// </summary>
    [DataField]
    public FixedPoint2 CpuPerApcPerSecond = 0.17;

    /// <summary>
    /// Server-side accumulator for the APC income ticks.
    /// </summary>
    public float Accumulator;

    /// <summary>
    /// Number of hacked APCs required before the Doomsday device can be bought.
    /// </summary>
    [DataField]
    public int DoomsdayRequiredApcs = 8;

    /// <summary>
    /// The store currency used for malf abilities.
    /// </summary>
    [DataField]
    public ProtoId<CurrencyPrototype> Currency = "MalfCpu";

    /// <summary>
    /// Store categories shown in the malf ability store.
    /// </summary>
    [DataField]
    public List<ProtoId<StoreCategoryPrototype>> StoreCategories = new()
    {
        "MalfAiAbilities",
    };

    /// <summary>
    /// Action that opens the ability store.
    /// </summary>
    [DataField]
    public EntProtoId OpenStoreAction = "ActionMalfOpenStore";

    /// <summary>
    /// Entity of the granted open-store action, tracked for removal.
    /// </summary>
    [DataField]
    public EntityUid? OpenStoreActionEntity;

    /// <summary>
    /// Cyborgs this AI has subverted, shown in the malf borgs window.
    /// </summary>
    [DataField]
    public List<EntityUid> HackedCyborgs = new();

    /// <summary>
    /// Action that opens the subverted-cyborgs window.
    /// </summary>
    [DataField]
    public EntProtoId OpenBorgsAction = "ActionMalfOpenBorgsUi";

    /// <summary>
    /// Entity of the granted borgs-window action, tracked for removal.
    /// </summary>
    [DataField]
    public EntityUid? OpenBorgsActionEntity;

    /// <summary>
    /// Whether the Doomsday device has already been used this round.
    /// </summary>
    [DataField, ViewVariables(VVAccess.ReadWrite), AutoNetworkedField]
    public bool DoomsdayUsed;

    /// <summary>
    /// HUD alert showing the current processing power.
    /// </summary>
    [DataField]
    public ProtoId<AlertPrototype> PowerAlert = "MalfunctionProcessingPower";
}
