// SPDX-FileCopyrightText: 2025 Tyranex <bobthezombie4@gmail.com>
// SPDX-FileCopyrightText: 2025 Goob-Station
//
// SPDX-License-Identifier: MIT

using System.Linq;
using System.Numerics;
using Content.Client.Stylesheets;
using Content.Shared.Speech;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Funkystation.MalfAI.VoiceModulator;

[GenerateTypedNameReferences]
public sealed partial class MalfVoiceModulatorWindow : DefaultWindow
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;

    /// <summary>
    /// Raised with the chosen name, optional SpeechVerbPrototype id and optional JobIconPrototype id.
    /// </summary>
    public event Action<string, string?, string?>? OnNameSubmitted;

    private readonly SpriteSystem _spriteSystem;

    private string? _verb;
    private string? _jobIcon;

    private readonly ButtonGroup _jobIconButtonGroup = new();

    private const int JobIconColumnCount = 10;

    public MalfVoiceModulatorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _spriteSystem = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();

        ConfirmButton.OnPressed += _ => Submit();
        NameInput.OnTextEntered += _ => Submit();

        SpeechVerbSelector.OnItemSelected += args =>
        {
            _verb = (string?) SpeechVerbSelector.GetItemMetadata(args.Id);
            SpeechVerbSelector.SelectId(args.Id);
        };

        LoadVerbs();
        LoadJobIcons();
    }

    private void LoadVerbs()
    {
        var verbs = new List<(string, string)>();
        foreach (var verb in _protoManager.EnumeratePrototypes<SpeechVerbPrototype>())
        {
            verbs.Add((Loc.GetString(verb.Name), verb.ID));
        }

        verbs.Sort((a, b) => string.Compare(a.Item1, b.Item1, StringComparison.CurrentCulture));

        SpeechVerbSelector.Clear();
        AddVerb(Loc.GetString("chat-speech-verb-name-none"), null);
        foreach (var (name, id) in verbs)
        {
            AddVerb(name, id);
        }
    }

    private void AddVerb(string name, string? verb)
    {
        var id = SpeechVerbSelector.ItemCount;
        SpeechVerbSelector.AddItem(name);
        if (verb is { } metadata)
            SpeechVerbSelector.SetItemMetadata(id, metadata);
    }

    /// <summary>
    /// Job icon grid, mirroring the voice mask window (GabyStation radio icons).
    /// </summary>
    private void LoadJobIcons()
    {
        var icons = _protoManager.EnumeratePrototypes<JobIconPrototype>()
            .Where(icon => icon.AllowSelection)
            .ToList();

        icons.Sort((x, y) => string.Compare(x.LocalizedJobName, y.LocalizedJobName, StringComparison.CurrentCulture));

        IconGrid.DisposeAllChildren();

        for (var i = 0; i < icons.Count; i++)
        {
            var jobIcon = icons[i];

            var styleBase = StyleBase.ButtonOpenBoth;
            var mod = i % JobIconColumnCount;
            if (mod == 0)
                styleBase = StyleBase.ButtonOpenRight;
            else if (mod == JobIconColumnCount - 1)
                styleBase = StyleBase.ButtonOpenLeft;

            var jobIconButton = new Button
            {
                Access = AccessLevel.Public,
                StyleClasses = { styleBase },
                MaxSize = new Vector2(42, 28),
                Group = _jobIconButtonGroup,
                ToolTip = jobIcon.LocalizedJobName,
            };

            var jobIconTexture = new TextureRect
            {
                Texture = _spriteSystem.Frame0(jobIcon.Icon),
                TextureScale = new Vector2(2.5f, 2.5f),
                Stretch = TextureRect.StretchMode.KeepCentered,
            };

            jobIconButton.AddChild(jobIconTexture);
            jobIconButton.OnPressed += _ => _jobIcon = jobIcon.ID;

            IconGrid.AddChild(jobIconButton);
        }
    }

    private void Submit()
    {
        var name = NameInput.Text.Trim();
        if (!string.IsNullOrWhiteSpace(name))
            OnNameSubmitted?.Invoke(name, _verb, _jobIcon);
    }
}
