using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.IO;

namespace Content.Client._CorvaxGoob.Photo.UI;

[GenerateTypedNameReferences]
public sealed partial class ImageUi : DefaultWindow
{
    public ImageUi()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetImage(byte[] imageData)
    {
        try
        {
            MemoryStream stream = new MemoryStream(imageData);
            ImageDislay.Texture = Texture.LoadFromPNGStream(stream);
        }
        catch { }
    }
}
