- type: department
  id: Service
  name: department-Service
  description: department-Service-description
  color: "#9FED58"
  weight: 2
  roles:
  - Bartender
  - Botanist
  - Chef
  - HeadOfPersonnel # also head of civilian for entertainment etc jobs, but not a member of it because bleh
  - ServiceWorker
  - Rancher
