// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.UserInterface.Controls;
using Content.Shared._Hood.Phone;
using Content.Shared.Telephone;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Hood.Phone;

[GenerateTypedNameReferences]
public sealed partial class PhoneWindow : FancyWindow
{
    public event Action? EjectSimPressed;
    public event Action<uint, string>? SmsSendPressed;
    public event Action<uint>? DialPressed;
    public event Action? AcceptCallPressed;
    public event Action? RejectCallPressed;
    public event Action? HangupPressed;

    private PhoneBoundUserInterfaceState? _state;
    private uint? _selectedConversation;

    public PhoneWindow()
    {
        RobustXamlLoader.Load(this);

        EjectSimButton.OnPressed += _ => EjectSimPressed?.Invoke();
        ShowPhoneButton.OnPressed += _ => ShowApp(messages: false);
        ShowMessagesButton.OnPressed += _ => ShowApp(messages: true);

        DialButton.OnPressed += _ => TryDial();
        DialNumberInput.OnTextEntered += _ => TryDial();
        AcceptCallButton.OnPressed += _ => AcceptCallPressed?.Invoke();
        RejectCallButton.OnPressed += _ => RejectCallPressed?.Invoke();
        HangupButton.OnPressed += _ => HangupPressed?.Invoke();

        ConversationSelector.OnItemSelected += args =>
        {
            ConversationSelector.Select(args.Id);
            if (args.Button.GetItemMetadata(args.Id) is uint number)
                SelectConversation(number);
        };

        OpenConversationButton.OnPressed += _ => TryOpenConversation();
        MessageNumberInput.OnTextEntered += _ => TryOpenConversation();
        SendMessageButton.OnPressed += _ => TrySendMessage();
        MessageInput.OnTextEntered += _ => TrySendMessage();
    }

    public void UpdateState(PhoneBoundUserInterfaceState state)
    {
        _state = state;

        SimStatusLabel.Text = Loc.GetString(state.HasSim
            ? "hood-phone-ui-sim-ready"
            : "hood-phone-ui-no-sim");

        PhoneNumberLabel.Text = state.PhoneNumber is { } number
            ? Loc.GetString("hood-phone-ui-number", ("number", FormatNumber(number)))
            : Loc.GetString("hood-phone-ui-number-unavailable");

        EjectSimButton.Disabled = !state.HasSim;
        UpdateError(state.Error);
        UpdateCallState(state);

        if (!state.HasSim)
            _selectedConversation = null;

        RebuildConversationSelector();
        RenderMessages();
        UpdateMessageControls();
    }

    private void ShowApp(bool messages)
    {
        CallPanel.Visible = !messages;
        MessagesPanel.Visible = messages;
        ShowPhoneButton.Pressed = !messages;
        ShowMessagesButton.Pressed = messages;
    }

    private void TryDial()
    {
        if (!TryParseNumber(DialNumberInput.Text, out var number))
        {
            UpdateError(PhoneOperationError.InvalidNumber);
            return;
        }

        DialPressed?.Invoke(number);
    }

    private void TryOpenConversation()
    {
        if (!TryParseNumber(MessageNumberInput.Text, out var number))
        {
            UpdateError(PhoneOperationError.InvalidNumber);
            return;
        }

        SelectConversation(number);
        RebuildConversationSelector();
        RenderMessages();
        UpdateMessageControls();
    }

    private void SelectConversation(uint number)
    {
        _selectedConversation = number;
        MessageNumberInput.Text = FormatNumber(number);
        RenderMessages();
        UpdateMessageControls();
    }

    private void TrySendMessage()
    {
        if (_selectedConversation is not { } recipient)
        {
            if (!TryParseNumber(MessageNumberInput.Text, out recipient))
            {
                UpdateError(PhoneOperationError.InvalidNumber);
                return;
            }

            _selectedConversation = recipient;
        }

        var content = MessageInput.Text.Trim();
        if (content.Length == 0)
        {
            UpdateError(PhoneOperationError.EmptyMessage);
            return;
        }

        SmsSendPressed?.Invoke(recipient, content);
        MessageInput.Text = string.Empty;
    }

    private void UpdateCallState(PhoneBoundUserInterfaceState state)
    {
        var callStatus = state.CallDisposition switch
        {
            PhoneCallDisposition.Rejected when state.CallState is TelephoneState.Idle or TelephoneState.EndingCall
                => "hood-phone-ui-call-rejected",
            PhoneCallDisposition.Ended when state.CallState is TelephoneState.Idle or TelephoneState.EndingCall
                => "hood-phone-ui-call-ending",
            _ => state.CallState switch
            {
                TelephoneState.Calling => "hood-phone-ui-call-calling",
                TelephoneState.Ringing => "hood-phone-ui-call-ringing",
                TelephoneState.InCall => "hood-phone-ui-call-connected",
                TelephoneState.EndingCall => "hood-phone-ui-call-ending",
                _ => "hood-phone-ui-call-idle",
            },
        };

        CallStateLabel.Text = Loc.GetString(callStatus);

        CallPeerLabel.Text = state.CallPeerNumber is { } peer
            ? Loc.GetString("hood-phone-ui-call-peer", ("number", FormatNumber(peer)))
            : Loc.GetString("hood-phone-ui-call-no-peer");

        DialButton.Disabled = !state.HasSim || state.CallState != TelephoneState.Idle;
        DialNumberInput.Editable = state.HasSim && state.CallState == TelephoneState.Idle;
        AcceptCallButton.Disabled = !state.HasSim || state.CallState != TelephoneState.Ringing;
        RejectCallButton.Disabled = !state.HasSim || state.CallState != TelephoneState.Ringing;
        HangupButton.Disabled = !state.HasSim || state.CallState is TelephoneState.Idle or TelephoneState.EndingCall;
    }

    private void RebuildConversationSelector()
    {
        ConversationSelector.Clear();

        if (_state is not { HasSim: true } state)
        {
            ConversationSelector.AddItem(Loc.GetString("hood-phone-ui-no-conversations"));
            ConversationSelector.Disabled = true;
            return;
        }

        var numbers = new List<uint>(state.Conversations.Keys);
        if (_selectedConversation is { } selected && !numbers.Contains(selected))
            numbers.Add(selected);

        numbers.Sort();
        if (numbers.Count == 0)
        {
            ConversationSelector.AddItem(Loc.GetString("hood-phone-ui-no-conversations"));
            ConversationSelector.Disabled = true;
            return;
        }

        _selectedConversation ??= numbers[0];
        ConversationSelector.Disabled = false;

        foreach (var number in numbers)
        {
            ConversationSelector.AddItem(FormatNumber(number));
            var index = ConversationSelector.ItemCount - 1;
            ConversationSelector.SetItemMetadata(index, number);
            if (_selectedConversation == number)
                ConversationSelector.Select(index);
        }

        if (_selectedConversation is { } current)
            MessageNumberInput.Text = FormatNumber(current);
    }

    private void RenderMessages()
    {
        MessageList.RemoveAllChildren();

        if (_state is not { } state || _selectedConversation is not { } selected)
        {
            AddEmptyMessageLabel("hood-phone-ui-no-conversation");
            return;
        }

        if (!state.Conversations.TryGetValue(selected, out var messages) || messages.Count == 0)
        {
            AddEmptyMessageLabel("hood-phone-ui-no-messages");
            return;
        }

        foreach (var message in messages)
        {
            var own = message.SenderNumber == state.PhoneNumber;
            var sender = own
                ? Loc.GetString("hood-phone-ui-message-me")
                : FormatNumber(message.SenderNumber);
            var time = $"{(int) message.Timestamp.TotalHours:D2}:{message.Timestamp.Minutes:D2}";
            var failed = message.DeliveryFailed
                ? $" {Loc.GetString("hood-phone-ui-message-failed")}"
                : string.Empty;

            var label = new RichTextLabel
            {
                HorizontalExpand = true,
                Text = FormattedMessage.EscapeText($"[{time}] {sender}: {message.Content}{failed}"),
            };
            MessageList.AddChild(label);
        }
    }

    private void AddEmptyMessageLabel(string locId)
    {
        MessageList.AddChild(new Label
        {
            Text = Loc.GetString(locId),
            HorizontalAlignment = HAlignment.Center,
        });
    }

    private void UpdateMessageControls()
    {
        var enabled = _state is { HasSim: true };
        MessageNumberInput.Editable = enabled;
        OpenConversationButton.Disabled = !enabled;
        MessageInput.Editable = enabled && _selectedConversation != null;
        SendMessageButton.Disabled = !enabled || _selectedConversation == null;
    }

    private void UpdateError(PhoneOperationError error)
    {
        OperationErrorLabel.Visible = error != PhoneOperationError.None;
        OperationErrorLabel.Text = error switch
        {
            PhoneOperationError.NoSim => Loc.GetString("hood-phone-ui-error-no-sim"),
            PhoneOperationError.InvalidNumber => Loc.GetString("hood-phone-ui-error-invalid-number"),
            PhoneOperationError.SelfTarget => Loc.GetString("hood-phone-ui-error-self"),
            PhoneOperationError.Offline => Loc.GetString("hood-phone-ui-error-offline"),
            PhoneOperationError.Busy => Loc.GetString("hood-phone-ui-error-busy"),
            PhoneOperationError.InvalidState => Loc.GetString("hood-phone-ui-error-invalid-state"),
            PhoneOperationError.EmptyMessage => Loc.GetString("hood-phone-ui-error-empty-message"),
            PhoneOperationError.InvalidRequest => Loc.GetString("hood-phone-ui-error-invalid-request"),
            _ => string.Empty,
        };
    }

    private static string FormatNumber(uint number)
    {
        return $"H-{number:D4}";
    }

    private static bool TryParseNumber(string input, out uint number)
    {
        var normalized = input.Trim();
        if (normalized.StartsWith("H-", StringComparison.OrdinalIgnoreCase))
            normalized = normalized[2..];
        else if (normalized.StartsWith('#'))
            normalized = normalized[1..];

        return uint.TryParse(normalized, out number) && number > 0;
    }
}
