// SPDX-FileCopyrightText: 2022 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Illiux <newoutlook@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr.@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <Jezithyr@gmail.com>
// SPDX-FileCopyrightText: 2022 Jezithyr <jmaster9999@gmail.com>
// SPDX-FileCopyrightText: 2022 Júlio César Ueti <52474532+Mirino97@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Paul Ritter <ritter.paul1@googlemail.com>
// SPDX-FileCopyrightText: 2022 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2022 wrexbe <81056464+wrexbe@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 wrexbe <wrexbe@protonmail.com>
// SPDX-FileCopyrightText: 2024 Crotalus <Crotalus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared.Ghost;
using Content.Shared.Mobs;
using Content.Shared.Roles;
using Content.Shared.StatusIcon;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.GameObjects;
using Robust.Shared.IoC;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        private List<(string RawName, NetEntity Entity, GhostWarpType Type, int ObserverCount, string JobIconId, MobState MobState, string ProfessionTitle, GhostWarpHealthState HealthState, string DepartmentId)> _warps = new();
        private readonly Dictionary<NetEntity, ChipState> _entityToChip = new();

        private sealed record ChipState(ContainerButton Chip, StyleBoxFlat StyleBox, Label NameLabel, BoxContainer ObserverBlock, Label ObserverCountLabel, string ProfessionTitle, GhostWarpHealthState HealthState, string DepartmentId);
        private string _searchText = string.Empty;

        private enum ViewMode { Health, Department }
        private ViewMode _viewMode = ViewMode.Health;

        private static readonly string[] SectionTitleKeys = new[]
        {
            "ghost-target-window-filter-places",
            "ghost-target-window-filter-players",
            "ghost-target-window-filter-dead",
            "ghost-target-window-filter-ghosts",
            "ghost-target-window-filter-mobs"
        };

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;
        public event Action? RefreshPressed;

        private const string RefreshIconPath = "/Textures/Interface/VerbIcons/refresh.svg.192dpi.png";
        /// <summary>Ghost icon for "ghosts following" this target (Font Awesome ghost-solid, white for SS14).</summary>
        private const string ObserverIconPath = "/Textures/Interface/VerbIcons/ghost.svg.192dpi.png";
        /// <summary>Size for refresh and observer icons to match profession/job icon scale (job icon wrapper is 24 wide, chip height 26).</summary>
        private const float IconSize = 20f;

        public GhostTargetWindow()
        {
            RobustXamlLoader.Load(this);
            SearchBar.OnTextChanged += OnSearchTextChanged;
            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
            RefreshButton.OnPressed += _ => RefreshPressed?.Invoke();

            RefreshButton.RemoveAllChildren();
            var refreshIcon = new TextureRect
            {
                TexturePath = RefreshIconPath,
                MinSize = new Vector2(IconSize, IconSize),
                MaxSize = new Vector2(IconSize, IconSize),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center
            };
            RefreshButton.AddChild(refreshIcon);
            RefreshButton.TooltipSupplier = _ => new Tooltip { Text = Loc.GetString("ghost-target-window-refresh-tooltip") };

            ViewModeButton.OnPressed += CycleViewMode;
            UpdateViewModeButtonText();
        }

        public void UpdateWarps(IEnumerable<GhostWarp> warps)
        {
            _warps = warps
                .OrderBy(w => w.Type)
                .ThenBy(w => w.DisplayName, Comparer<string>.Create(
                    (x, y) => string.Compare(x, y, StringComparison.Ordinal)))
                .Select(w => (w.DisplayName, w.Entity, w.Type, w.ObserverCount, w.JobIconId, w.MobState, w.ProfessionTitle, w.HealthState, w.DepartmentId))
                .ToList();
        }

        private static Color GetColorForHealthState(GhostWarpHealthState healthState)
        {
            return healthState switch
            {
                GhostWarpHealthState.Healthy => new Color(0x50 / 255f, 0x91 / 255f, 0x21 / 255f),   // #509121 green
                GhostWarpHealthState.Wounded => new Color(0xda / 255f, 0x7b / 255f, 0x0c / 255f),   // #da7b0c orange
                GhostWarpHealthState.Critical => new Color(0xc6 / 255f, 0x1f / 255f, 0x1f / 255f),   // #c61f1f red
                _ => new Color(0x73 / 255f, 0x73 / 255f, 0x73 / 255f)                              // #737373 grey - dead/unknown
            };
        }

        /// <summary>SS13 orbit: department color from job. Prefer server-sent DepartmentId (language-independent, uses DepartmentPrototype.Color); fallback to profession title substring matching.</summary>
        private Color GetColorForDepartment(string? departmentId, string? professionTitle)
        {
            // SS14: use department prototype color when server sent department ID (works in any locale).
            if (!string.IsNullOrWhiteSpace(departmentId))
            {
                var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
                if (prototypeManager.TryIndex<DepartmentPrototype>(departmentId, out var dept))
                    return dept.Color;
            }
            // Fallback: match localized profession title (may fail in non-English).
            if (string.IsNullOrWhiteSpace(professionTitle))
                return new Color(0x73 / 255f, 0x73 / 255f, 0x73 / 255f); // grey
            var job = professionTitle.Trim();
            // SS13-like: cargo=brown, command=blue, engineering=orange, medical=teal, science=pink, security=red, service=green
            if (job.Contains("Cargo", StringComparison.OrdinalIgnoreCase) || job.Contains("Quartermaster", StringComparison.OrdinalIgnoreCase) || job.Contains("Miner", StringComparison.OrdinalIgnoreCase))
                return new Color(0xa5 / 255f, 0x52 / 255f, 0x2a / 255f);   // brown
            if (job.Contains("Captain", StringComparison.OrdinalIgnoreCase) || job.Contains("Head of Personnel", StringComparison.OrdinalIgnoreCase) || job.Contains("HoP", StringComparison.OrdinalIgnoreCase))
                return new Color(0x34 / 255f, 0x7b / 255f, 0xeb / 255f);   // blue
            if (job.Contains("Engineer", StringComparison.OrdinalIgnoreCase) || job.Contains("Atmospheric", StringComparison.OrdinalIgnoreCase) || job.Contains("CE", StringComparison.OrdinalIgnoreCase))
                return new Color(0xf9 / 255f, 0x80 / 255f, 0x1a / 255f);   // orange
            if (job.Contains("Medical", StringComparison.OrdinalIgnoreCase) || job.Contains("Doctor", StringComparison.OrdinalIgnoreCase) || job.Contains("CMO", StringComparison.OrdinalIgnoreCase) || job.Contains("Chemist", StringComparison.OrdinalIgnoreCase) || job.Contains("Paramedic", StringComparison.OrdinalIgnoreCase) || job.Contains("Coroner", StringComparison.OrdinalIgnoreCase))
                return new Color(0x2e / 255f, 0xcc / 255f, 0x71 / 255f);   // teal/green
            if (job.Contains("Science", StringComparison.OrdinalIgnoreCase) || job.Contains("Research", StringComparison.OrdinalIgnoreCase) || job.Contains("RD", StringComparison.OrdinalIgnoreCase) || job.Contains("Roboticist", StringComparison.OrdinalIgnoreCase) || job.Contains("Geneticist", StringComparison.OrdinalIgnoreCase) || job.Contains("Scientist", StringComparison.OrdinalIgnoreCase))
                return new Color(0xe9 / 255f, 0x5d / 255f, 0xbf / 255f);  // pink
            if (job.Contains("Security", StringComparison.OrdinalIgnoreCase) || job.Contains("HoS", StringComparison.OrdinalIgnoreCase) || job.Contains("Warden", StringComparison.OrdinalIgnoreCase) || job.Contains("Detective", StringComparison.OrdinalIgnoreCase))
                return new Color(0xc6 / 255f, 0x1f / 255f, 0x1f / 255f);   // red
            if (job.Contains("Service", StringComparison.OrdinalIgnoreCase) || job.Contains("Bartender", StringComparison.OrdinalIgnoreCase) || job.Contains("Chef", StringComparison.OrdinalIgnoreCase) || job.Contains("Cook", StringComparison.OrdinalIgnoreCase) || job.Contains("Botanist", StringComparison.OrdinalIgnoreCase) || job.Contains("Janitor", StringComparison.OrdinalIgnoreCase) || job.Contains("Chaplain", StringComparison.OrdinalIgnoreCase) || job.Contains("Clown", StringComparison.OrdinalIgnoreCase) || job.Contains("Mime", StringComparison.OrdinalIgnoreCase) || job.Contains("Curator", StringComparison.OrdinalIgnoreCase) || job.Contains("Lawyer", StringComparison.OrdinalIgnoreCase) || job.Contains("Psychologist", StringComparison.OrdinalIgnoreCase))
                return new Color(0x2e / 255f, 0xcc / 255f, 0x71 / 255f);  // green (service)
            return new Color(0x73 / 255f, 0x73 / 255f, 0x73 / 255f);       // grey
        }

        private Color GetDisplayColor(ViewMode mode, GhostWarpHealthState healthState, string professionTitle, string departmentId)
        {
            return mode == ViewMode.Department
                ? GetColorForDepartment(departmentId, professionTitle)
                : GetColorForHealthState(healthState);
        }

        private void CycleViewMode(BaseButton.ButtonEventArgs _)
        {
            _viewMode = _viewMode == ViewMode.Health ? ViewMode.Department : ViewMode.Health;
            UpdateViewModeButtonText();
            foreach (var state in _entityToChip.Values)
            {
                var color = GetDisplayColor(_viewMode, state.HealthState, state.ProfessionTitle, state.DepartmentId);
                state.StyleBox.BackgroundColor = color;
            }
        }

        private void UpdateViewModeButtonText()
        {
            var key = _viewMode == ViewMode.Health ? "ghost-target-window-color-mode-health" : "ghost-target-window-color-mode-department";
            ViewModeButton.Text = Loc.GetString(key);
            ViewModeButton.TooltipSupplier = _ => new Tooltip { Text = Loc.GetString("ghost-target-window-color-mode-tooltip") };
        }

        private static Color LightenForHover(Color color, float factor = 1.2f)
        {
            return new Color(
                Math.Min(1f, color.R * factor),
                Math.Min(1f, color.G * factor),
                Math.Min(1f, color.B * factor),
                color.A);
        }

        public void UpdateObserverCount(NetEntity entity, int count)
        {
            for (var i = 0; i < _warps.Count; i++)
            {
                if (_warps[i].Entity != entity)
                    continue;
                var (rawName, _, type, _, jobIconId, mobState, professionTitle, healthState, departmentId) = _warps[i];
                _warps[i] = (rawName, entity, type, count, jobIconId, mobState, professionTitle, healthState, departmentId);
                if (_entityToChip.TryGetValue(entity, out var state))
                {
                    state.NameLabel.Text = rawName;
                    state.ObserverCountLabel.Text = count.ToString();
                    state.ObserverBlock.Visible = count > 0;
                }
                return;
            }
        }

        public void Populate()
        {
            _entityToChip.Clear();
            SectionsContainer.DisposeAllChildren();

            var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
            var spriteSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<SpriteSystem>();

            foreach (var type in new[] { GhostWarpType.Player, GhostWarpType.Dead, GhostWarpType.Ghost, GhostWarpType.Mob, GhostWarpType.Location })
            {
                var titleKey = SectionTitleKeys[(int) type];
                var body = new CollapsibleBody();
                var wrap = new WrapContainer { SeparationOverride = 6, HorizontalExpand = true };
                body.AddChild(wrap);

                var collapsible = new Collapsible(
                    new CollapsibleHeading(Loc.GetString(titleKey)),
                    body);
                collapsible.BodyVisible = true;
                SectionsContainer.AddChild(collapsible);

                foreach (var (rawName, warpTarget, warpType, observerCount, jobIconId, mobState, professionTitle, healthState, departmentId) in _warps)
                {
                    if (warpType != type)
                        continue;

                    var bgColor = GetDisplayColor(_viewMode, healthState, professionTitle ?? string.Empty, departmentId ?? string.Empty);
                    var entity = warpTarget;

                    var styleBox = new StyleBoxFlat
                    {
                        BackgroundColor = bgColor,
                        ContentMarginLeftOverride = 4,
                        ContentMarginRightOverride = 6,
                        ContentMarginTopOverride = 2,
                        ContentMarginBottomOverride = 2,
                    };

                    var chip = new ContainerButton
                    {
                        StyleBoxOverride = styleBox,
                        MinSize = new Vector2(0, 26),
                    };
                    chip.OnMouseEntered += _ =>
                    {
                        if (_entityToChip.TryGetValue(entity, out var s))
                            styleBox.BackgroundColor = LightenForHover(GetDisplayColor(_viewMode, s.HealthState, s.ProfessionTitle, s.DepartmentId));
                    };
                    chip.OnMouseExited += _ =>
                    {
                        if (_entityToChip.TryGetValue(entity, out var s))
                            styleBox.BackgroundColor = GetDisplayColor(_viewMode, s.HealthState, s.ProfessionTitle, s.DepartmentId);
                    };

                    var content = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        SeparationOverride = 4,
                    };

                    if (!string.IsNullOrEmpty(jobIconId) && prototypeManager.TryIndex<JobIconPrototype>(jobIconId, out var jobIcon))
                    {
                        try
                        {
                            var texture = spriteSystem.Frame0(jobIcon.Icon);
                            var iconWrapper = new BoxContainer
                            {
                                Orientation = BoxContainer.LayoutOrientation.Vertical,
                                MinSize = new Vector2(24, 0),
                                VerticalExpand = true,
                            };
                            var iconRect = new TextureRect
                            {
                                Texture = texture,
                                HorizontalExpand = true,
                                VerticalExpand = true,
                                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                                CanShrink = true,
                            };
                            iconWrapper.AddChild(iconRect);
                            content.AddChild(iconWrapper);
                        }
                        catch
                        {
                            // Ignore missing/ invalid job icon
                        }
                    }

                    var nameLabel = new Label
                    {
                        Text = rawName,
                        VerticalAlignment = VAlignment.Center,
                        ClipText = false,
                        HorizontalExpand = true,
                    };
                    content.AddChild(nameLabel);

                    // Observer count and icon to the right of the entity name
                    var observerBlock = new BoxContainer
                    {
                        Orientation = BoxContainer.LayoutOrientation.Horizontal,
                        SeparationOverride = 2,
                        VerticalAlignment = VAlignment.Center,
                        Visible = observerCount > 0,
                    };
                    var observerIcon = new TextureRect
                    {
                        TexturePath = ObserverIconPath,
                        MinSize = new Vector2(IconSize, IconSize),
                        MaxSize = new Vector2(IconSize, IconSize),
                        Stretch = TextureRect.StretchMode.KeepAspectCentered,
                        VerticalAlignment = VAlignment.Center,
                    };
                    observerBlock.AddChild(observerIcon);
                    var observerCountLabel = new Label
                    {
                        Text = observerCount.ToString(),
                        VerticalAlignment = VAlignment.Center,
                        ClipText = false,
                    };
                    observerBlock.AddChild(observerCountLabel);
                    content.AddChild(observerBlock);

                    chip.AddChild(content);
                    chip.OnPressed += _ => WarpClicked?.Invoke(warpTarget);
                    if (!string.IsNullOrEmpty(professionTitle))
                        chip.TooltipSupplier = _ => new Tooltip { Text = professionTitle };
                    chip.Visible = ButtonIsVisible(rawName, professionTitle, departmentId);
                    _entityToChip[warpTarget] = new ChipState(chip, styleBox, nameLabel, observerBlock, observerCountLabel, professionTitle ?? string.Empty, healthState, departmentId ?? string.Empty);
                    wrap.AddChild(chip);
                }
            }
        }

        /// <summary>SS13 orbit: isJobCkeyOrNameMatch filters by full_name, name, job, ckey. We filter by display name, profession (job) from ID, and department.</summary>
        private bool ButtonIsVisible(string? displayName, string? professionTitle, string? departmentId)
        {
            if (string.IsNullOrWhiteSpace(_searchText))
                return true;
            var query = _searchText.Trim();
            if (displayName != null && displayName.Contains(query, StringComparison.OrdinalIgnoreCase))
                return true;
            if (professionTitle != null && professionTitle.Contains(query, StringComparison.OrdinalIgnoreCase))
                return true;
            // Match department ID (e.g. "Engineering") and localized department name.
            if (!string.IsNullOrWhiteSpace(departmentId))
            {
                if (departmentId.Contains(query, StringComparison.OrdinalIgnoreCase))
                    return true;
                var prototypeManager = IoCManager.Resolve<IPrototypeManager>();
                if (prototypeManager.TryIndex<DepartmentPrototype>(departmentId, out var dept))
                {
                    var departmentName = Loc.GetString(dept.Name);
                    if (departmentName.Contains(query, StringComparison.OrdinalIgnoreCase))
                        return true;
                }
            }
            return false;
        }

        private void UpdateVisibleButtons()
        {
            foreach (var state in _entityToChip.Values)
                state.Chip.Visible = ButtonIsVisible(state.NameLabel.Text, state.ProfessionTitle, state.DepartmentId);
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;
            UpdateVisibleButtons();
            GhostScroll.SetScrollValue(Vector2.Zero);
        }
    }
}
