using Content.Client.UserInterface.Controls;
using Content.Goobstation.Shared.MalfunctionAi;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Goobstation.Client.MalfunctionAi;

[GenerateTypedNameReferences]
public sealed partial class MalfBorgsWindow : FancyWindow
{
    private static readonly Color AliveColor = Color.FromHex("#3fda52");
    private static readonly Color DeadColor = Color.FromHex("#d64040");

    public MalfBorgsWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(List<MalfBorgEntry> borgs)
    {
        BorgsList.RemoveAllChildren();

        if (borgs.Count == 0)
        {
            BorgsList.AddChild(new Label
            {
                Text = Loc.GetString("malfunction-ai-borgs-window-empty"),
            });
            return;
        }

        foreach (var borg in borgs)
        {
            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                Margin = new Thickness(0, 2),
            };

            row.AddChild(new Label
            {
                Text = borg.Name,
                HorizontalExpand = true,
            });

            row.AddChild(new Label
            {
                Text = Loc.GetString(borg.Alive
                    ? "malfunction-ai-borgs-window-alive"
                    : "malfunction-ai-borgs-window-dead"),
                FontColorOverride = borg.Alive ? AliveColor : DeadColor,
                Margin = new Thickness(8, 0),
            });

            // Beacon locations come with [color] markup, so they need a rich text label.
            var location = new RichTextLabel
            {
                Margin = new Thickness(8, 0, 0, 0),
            };
            location.SetMessage(FormattedMessage.FromMarkupPermissive(borg.Location));
            row.AddChild(location);

            BorgsList.AddChild(row);
        }
    }
}
