using Content.Shared._Pirate.Plumbing;
using Content.Shared.Chemistry.Reagent;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._Pirate.Plumbing.UI;

[GenerateTypedNameReferences]
public sealed partial class PlumbingSynthesizerWindow : DefaultWindow
{
    [Dependency] private IPrototypeManager _prototypeManager = default!;

    public event Action<bool>? OnToggle;
    public event Action<string?>? OnSelectReagent;

    private bool _enabled = true;
    private readonly Dictionary<int, string> _reagentIndexMap = new();

    public PlumbingSynthesizerWindow()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        ToggleStatusButton.OnPressed += _ =>
        {
            _enabled = !_enabled;
            UpdateToggleButton();
            OnToggle?.Invoke(_enabled);
        };

        ReagentSelector.OnItemSelected += args =>
        {
            if (args.Id == 0)
            {
                OnSelectReagent?.Invoke(null);
            }
            else if (_reagentIndexMap.TryGetValue(args.Id, out var reagentId))
            {
                OnSelectReagent?.Invoke(reagentId);
            }
        };
    }

    private void UpdateToggleButton()
        => ToggleStatusButton.Text = _enabled
            ? Loc.GetString("plumbing-synthesizer-enabled")
            : Loc.GetString("plumbing-synthesizer-disabled");

    public void UpdateState(PlumbingSynthesizerBoundUserInterfaceState state)
    {
        _enabled = state.Enabled;
        UpdateToggleButton();

        BatteryBar.Value = state.BatteryCharge;

        _reagentIndexMap.Clear();
        ReagentSelector.Clear();

        ReagentSelector.AddItem(Loc.GetString("plumbing-synthesizer-none"), 0);

        var sortedReagents = new List<(string Id, string Name)>();
        foreach (var reagentId in state.GeneratableReagents.Keys)
        {
            sortedReagents.Add((reagentId, GetLocalizedReagentName(reagentId)));
        }

        sortedReagents.Sort((a, b) => string.Compare(a.Name, b.Name, StringComparison.CurrentCulture));

        var idx = 1;
        var selectedIdx = 0;
        foreach (var reagent in sortedReagents)
        {
            var reagentId = reagent.Id;
            var powerDrain = state.GeneratableReagents[reagentId];
            var label = $"{reagent.Name} ({powerDrain:F1}W/u)";
            ReagentSelector.AddItem(label, idx);
            _reagentIndexMap[idx] = reagentId;

            if (state.SelectedReagent == reagentId)
                selectedIdx = idx;

            idx++;
        }

        ReagentSelector.SelectId(selectedIdx);
    }

    private string GetLocalizedReagentName(string reagentId)
        => _prototypeManager.TryIndex<ReagentPrototype>(reagentId, out var reagent)
            ? reagent.LocalizedName
            : reagentId;
}
