// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Goobstation.Shared.Ghost.ObserverHud;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Goobstation.Client.Ghost.ObserverHud;

/// <summary>
/// Popup window that lets a regular ghost choose which observer HUD overlays to see.
/// It converts the checkbox selection into <see cref="GhostObserverHudVisuals"/> flags
/// and notifies the UI controller whenever the player changes the selection.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class GhostObserverHudPopup : Popup
{
    public event Action<GhostObserverHudVisuals>? VisualsChanged;

    public GhostObserverHudPopup()
    {
        RobustXamlLoader.Load(this);

        JobMindshieldCheckBox.OnToggled += OnCheckBoxToggled;
        HealthCheckBox.OnToggled += OnCheckBoxToggled;
        CriminalRecordsCheckBox.OnToggled += OnCheckBoxToggled;
    }

    // Clearing the checkboxes from code does not trigger OnToggled
    public void ClearSelection() =>
        JobMindshieldCheckBox.Pressed = HealthCheckBox.Pressed = CriminalRecordsCheckBox.Pressed = false;

    private void OnCheckBoxToggled(ButtonToggledEventArgs _) =>
        VisualsChanged?.Invoke(GetVisuals());

    // Each checked box adds its HUD flag; unchecked boxes add None
    private GhostObserverHudVisuals GetVisuals() =>
        (JobMindshieldCheckBox.Pressed ? GhostObserverHudVisuals.JobMindshield : GhostObserverHudVisuals.None) |
        (HealthCheckBox.Pressed ? GhostObserverHudVisuals.Health : GhostObserverHudVisuals.None) |
        (CriminalRecordsCheckBox.Pressed ? GhostObserverHudVisuals.CriminalRecords : GhostObserverHudVisuals.None);
}
