// SPDX-FileCopyrightText: 2025 Tyranex <bobthezombie4@gmail.com>
// SPDX-FileCopyrightText: 2025 Goob-Station
//
// SPDX-License-Identifier: MIT

using System.Linq;
using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.MalfAI.Borgs;
using Content.Shared.DoAfter;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._Funkystation.MalfAI.Borgs;
// I WILL REWORK THAT
public sealed partial class MalfAiBorgsWindow : FancyWindow
{
    private readonly MalfAiBorgsBoundUserInterface _bui;
    private readonly IGameTiming _timing;
    private readonly IEntityManager _entMan;

    private readonly BoxContainer? _borgList;
    private readonly Label? _noBorgs;
    private readonly Button? _masterLawsetButton;
    private readonly Button? _resyncAllButton;

    private readonly Dictionary<NetEntity, ProgressBar> _claimBars = new();

    // Purely for instant visual feedback before the first server state arrives after clicking Claim.
    private readonly HashSet<NetEntity> _localPending = [];

    private MalfAiBorgsUiState? _lastState;

    public MalfAiBorgsWindow(MalfAiBorgsBoundUserInterface bui)
    {
        _bui = bui;
        _timing = IoCManager.Resolve<IGameTiming>();
        _entMan = IoCManager.Resolve<IEntityManager>();
        RobustXamlLoader.Load(this);

        _borgList = FindControl<BoxContainer>("BorgList");
        _noBorgs = FindControl<Label>("NoBorgs");
        _masterLawsetButton = FindControl<Button>("MasterLawsetButton");
        _resyncAllButton = FindControl<Button>("ResyncAllButton");

        if (_masterLawsetButton != null)
            _masterLawsetButton.OnPressed += _ => _bui.SendOpenMasterLawset();
        if (_resyncAllButton != null)
            _resyncAllButton.OnPressed += _ => _bui.SendResyncAll();
    }

    public void UpdateState(MalfAiBorgsUiState state)
    {
        if (_borgList == null)
            return;

        _lastState = state;

        // Once the server confirms a claim (or it's resolved), drop the local pending flag.
        foreach (var entry in state.Borgs)
        {
            if (entry.IsBeingClaimed || entry.OwnedByMe)
                _localPending.Remove(entry.Borg);
        }

        RebuildRows(state);
    }

    private void RebuildRows(MalfAiBorgsUiState state)
    {
        if (_borgList == null)
            return;

        _claimBars.Clear();
        _borgList.RemoveAllChildren();

        if (state.Borgs.Count == 0)
        {
            if (_noBorgs != null)
                _noBorgs.Visible = true;
            return;
        }

        if (_noBorgs != null)
            _noBorgs.Visible = false;

        var anyClaimActive = state.Borgs.Any(b => b.IsBeingClaimed) || _localPending.Count > 0;

        foreach (var entry in state.Borgs)
            _borgList.AddChild(CreateBorgRow(entry, anyClaimActive));

        if (_resyncAllButton != null)
            _resyncAllButton.Visible = state.Borgs.Any(b => b.OwnedByMe && b.IsSynced);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        foreach (var (borgNet, bar) in _claimBars)
            bar.Value = GetClaimProgress(borgNet);
    }

    // Reads progress from the AI's networked DoAfterComponent so it stays in sync with the server.
    private float GetClaimProgress(NetEntity borgNet)
    {
        if (!_entMan.TryGetComponent<DoAfterComponent>(_bui.Owner, out var doAfterComp))
            return 0f;

        foreach (var doAfter in doAfterComp.DoAfters.Values)
        {
            if (doAfter.CancelledTime != null || doAfter.Completed)
                continue;
            if (doAfter.Args.Event is not MalfAiClaimBorgDoAfterEvent claimEvent)
                continue;
            if (claimEvent.Borg != borgNet)
                continue;

            var elapsed = _timing.CurTime - doAfter.StartTime;
            return (float) Math.Clamp(elapsed.TotalSeconds / doAfter.Args.Delay.TotalSeconds, 0.0, 1.0);
        }

        return 0f;
    }

    private Control CreateBorgRow(MalfAiBorgListEntry entry, bool anyClaimActive)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 2),
        };

        var healthBar = new ProgressBar
        {
            MinValue = 0f, MaxValue = 1f, Value = entry.HealthFraction,
            MinWidth = 60, MaxWidth = 60,
            ForegroundStyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = entry.HealthFraction switch
                {
                    > 0.6f => Color.Green,
                    > 0.3f => Color.Yellow,
                    _ => Color.Red,
                }
            }
        };

        var nameLabel = new Label
        {
            Text = entry.Name,
            HorizontalExpand = true,
            Margin = new Thickness(4, 0),
        };

        container.AddChild(healthBar);
        container.AddChild(nameLabel);

        if (entry.OwnedByMe)
        {
            var syncCheck = new CheckBox
            {
                Text = Loc.GetString("malfai-borgs-sync-label"),
                Pressed = entry.IsSynced,
            };
            syncCheck.OnToggled += args => _bui.SendSetSync(entry.Borg, args.Pressed);

            var jumpButton = new Button { Text = Loc.GetString("malfai-borgs-jump-label") };
            jumpButton.OnPressed += _ => _bui.SendJumpToBorg(entry.Borg);

            container.AddChild(syncCheck);
            container.AddChild(jumpButton);
        }
        else if (!entry.IsOwned)
        {
            // Show bar when server confirmed OR locally pending (covers round-trip gap).
            if (entry.IsBeingClaimed || _localPending.Contains(entry.Borg))
            {
                var bar = new ProgressBar
                {
                    MinValue = 0f, MaxValue = 1f, Value = 0f,
                    MinWidth = 80, MaxWidth = 80,
                    ForegroundStyleBoxOverride = new StyleBoxFlat { BackgroundColor = Color.CornflowerBlue },
                };
                _claimBars[entry.Borg] = bar;
                container.AddChild(bar);
            }
            else if (!anyClaimActive)
            {
                var claimButton = new Button { Text = Loc.GetString("malfai-borgs-claim-label") };
                claimButton.OnPressed += _ =>
                {
                    _localPending.Add(entry.Borg);
                    _bui.SendClaimBorg(entry.Borg);
                    if (_lastState != null)
                        RebuildRows(_lastState);
                };
                container.AddChild(claimButton);
            }
        }

        return container;
    }
}
