# SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
# SPDX-FileCopyrightText: 2024 SlamBamActionman <83650252+SlamBamActionman@users.noreply.github.com>
# SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested]

jobs:
  add_label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write # AltHub Space
    steps:
    # AltHub Space -> start
    - uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const issue_number = context.issue.number;

          await github.rest.issues.addLabels({
            owner,
            repo,
            issue_number,
            labels: ["S: Needs Review"],
          });

          try {
            await github.rest.issues.removeLabel({
              owner,
              repo,
              issue_number,
              name: "S: Awaiting Changes",
            });
          } catch (error) {
            if (error.status !== 404) {
              throw error;
            }
          }
    # AltHub Space -> end
