# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuitBlack
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlack

- type: loadout
  id: HeadofSecurityJumpskirtBlack
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSBlack
    
#Shoulder Mantle
- type: loadout
  id: ClothingNeckMantleHOSShoulder
  equipment:
    neck: ClothingNeckMantleHOSShoulder
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS

- type: loadout
  id: HeadofSecurityCloakExperimental
  effects:
  - !type:GroupLoadoutEffect
    proto: MasterHoS
  equipment:
    neck: ClothingNeckCloakHosExperimental
